const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(d).toLocaleString('pt-BR',{timeZone:'America/Fortaleza'}):'-';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
async function api(url,opt={}){const r=await fetch(url,opt),t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.error||d?.message||`Erro ${r.status}`);return d}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),3500)}
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
let contacts=[],groups=[],campaigns=[],orders=[],messages=[],_steps=[],_import=[];
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');({home:loadHome,contacts:loadContacts,campaigns:loadCampaigns,execution:loadExecution,returns:loadReturns,purchases:loadPurchases,settings:loadSettings}[id]?.())}
async function refreshStatus(){try{const s=await api('/api/status');$('#waBadge').textContent=s.connected?`WhatsApp conectado • ${s.number||''}`:s.starting?'WhatsApp conectando…':'WhatsApp desconectado';$('#waBadge').className='badge'}catch{}}
async function loadHome(){try{const d=await api('/api/dashboard');const cards=[['Contatos ativos',d.contacts],['Campanhas',d.campaigns],['Na fila',d.queue],['Enviadas',d.sent],['Entregues',d.delivered],['Lidas',d.read],['Retornos',d.returns],['Pedidos',d.orders],['Comprovantes',d.proofs],['Compras',d.completed],['Receita',money(d.revenue)],['Alertas',d.alerts]];$('#dashboard').innerHTML=cards.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#ops').innerHTML=`<p><span class="status ${d.connected?'ok':'bad'}">WhatsApp: ${d.connected?'conectado':'desconectado'} ${d.number?'• '+esc(d.number):''}</span> <span class="status ${d.alerts?'warn':'ok'}">Alertas: ${d.alerts}</span> <span class="status ${d.active_campaigns?'ok':'warn'}">Campanhas ativas: ${d.active_campaigns}</span></p>`;$('#funnel').innerHTML=`<div class="funnel"><div><strong>${d.sent}</strong>Envios</div><div><strong>${d.returns}</strong>Respostas</div><div><strong>${d.intents}</strong>Interesses</div><div><strong>${d.completed}</strong>Compras</div></div>`}catch(e){toast(e.message)}refreshStatus()}

async function loadGroups(){groups=await api('/api/groups')}
async function loadContacts(){try{[contacts]=await Promise.all([api('/api/contacts'),loadGroups()]);$('#contactGroupFilter').innerHTML='<option value="">Todos os grupos</option>'+groups.map(g=>`<option>${esc(g.name)}</option>`).join('');renderContacts()}catch(e){toast(e.message)}}
function renderContacts(){const q=($('#contactSearch')?.value||'').toLowerCase(),g=$('#contactGroupFilter')?.value||'';const l=contacts.filter(c=>(!g||c.group_name===g)&&(!q||[c.name,c.phone,c.city,c.tags,c.group_name].join(' ').toLowerCase().includes(q)));$('#contactsList').innerHTML=`<div class="tablewrap"><table class="table"><thead><tr><th>Cliente</th><th>WhatsApp</th><th>Grupo / tags</th><th>Origem</th><th>Status</th><th>Ações</th></tr></thead><tbody>${l.map(c=>`<tr><td><b>${esc(c.name)}</b><br><small>${esc(c.city||'')}</small></td><td>${esc(c.phone)}</td><td>${esc(c.group_name)}<br><small>${esc(c.tags||'')}</small></td><td>${esc(c.origin)}</td><td><span class="status ${c.opted_out?'bad':c.whatsapp_validated?'ok':'warn'}">${c.opted_out?'NÃO RECEBER':c.whatsapp_validated?'VALIDADO':'NÃO VALIDADO'}</span></td><td><button onclick="openContact('${c.id}')">Editar</button> <button onclick="validateOne('${c.id}')">Validar</button> <button class="danger" onclick="deleteContact('${c.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`||'<div class="empty">Nenhum contato.</div>'}
async function openContact(id=''){if(!groups.length)await loadGroups();const c=contacts.find(x=>x.id===id)||{};showModal(`<h2>${id?'Editar':'Novo'} contato</h2><div class="grid2"><div class="field"><label>Nome</label><input id="ctName" value="${esc(c.name||'')}"></div><div class="field"><label>WhatsApp</label><input id="ctPhone" value="${esc(c.phone||'')}"></div><div class="field"><label>Grupo</label><select id="ctGroup">${groups.map(g=>`<option ${g.name===c.group_name?'selected':''}>${esc(g.name)}</option>`).join('')}<option value="__NEW__">+ Criar novo grupo</option></select></div><div class="field"><label>Cidade</label><input id="ctCity" value="${esc(c.city||'')}"></div><div class="field"><label>Tags comerciais</label><input id="ctTags" value="${esc(c.tags||'')}" placeholder="vip, compra frequente, bairro centro"></div><div class="field"><label>Status</label><select id="ctStatus"><option ${c.status==='ATIVO'?'selected':''}>ATIVO</option><option ${c.status==='INATIVO'?'selected':''}>INATIVO</option></select></div></div><div class="field"><label>Observação</label><textarea id="ctNotes">${esc(c.notes||'')}</textarea></div><label class="check"><input id="ctOptout" type="checkbox" ${c.opted_out?'checked':''}> Não receber campanhas automáticas</label><div class="actions"><button class="primary" onclick="saveContact('${id}')">Salvar contato</button></div>`);$('#ctGroup').addEventListener('change',async e=>{if(e.target.value==='__NEW__'){const n=prompt('Nome do novo grupo:');if(n){try{await api('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})});await loadGroups();e.target.innerHTML=groups.map(g=>`<option>${esc(g.name)}</option>`).join('')+'<option value="__NEW__">+ Criar novo grupo</option>';e.target.value=n.toUpperCase()}catch(er){toast(er.message)}}}})}
async function saveContact(id){try{const b={name:$('#ctName').value,phone:$('#ctPhone').value,group_name:$('#ctGroup').value,city:$('#ctCity').value,tags:$('#ctTags').value,status:$('#ctStatus').value,notes:$('#ctNotes').value,opted_out:$('#ctOptout').checked};await api(id?`/api/contacts/${id}`:'/api/contacts',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();toast('Contato salvo.');loadContacts()}catch(e){toast(e.message)}}
async function deleteContact(id){if(!confirm('Excluir contato?'))return;try{await api(`/api/contacts/${id}`,{method:'DELETE'});loadContacts()}catch(e){toast(e.message)}}
async function validateOne(id){try{const r=await api('/api/contacts/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[id]})});toast(r.valid?'WhatsApp validado.':'Número não validado no WhatsApp.');loadContacts()}catch(e){toast(e.message)}}

function parseVCF(text){const unfolded=text.replace(/\r?\n[ \t]/g,'');const cards=unfolded.split(/BEGIN:VCARD/i).slice(1);const out=[];for(const c of cards){const fn=(c.match(/\nFN(?:;[^:]*)?:(.*)/i)||[])[1]?.trim()||'';const n=(c.match(/\nN(?:;[^:]*)?:(.*)/i)||[])[1]?.split(';').filter(Boolean).reverse().join(' ').trim()||'';const tels=[...c.matchAll(/\nTEL(?:;[^:]*)?:(.*)/gi)].map(m=>m[1].trim());for(const tel of tels)out.push({name:fn||n||'SEM NOME',phone:tel})}return out}
function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const rows=lines.map(l=>l.split(sep).map(x=>x.replace(/^"|"$/g,'').trim()));const h=rows[0].map(x=>x.toLowerCase()),ni=h.findIndex(x=>/nome|name/.test(x)),pi=h.findIndex(x=>/telefone|phone|whatsapp|celular|mobile/.test(x));const start=pi>=0?1:0;return rows.slice(start).map(r=>({name:ni>=0?r[ni]:'SEM NOME',phone:pi>=0?r[pi]:r.find(x=>/\d{8,}/.test(x))||''})).filter(x=>x.phone)}
async function openImport(){if(!groups.length)await loadGroups();showModal(`<h2>Importação inteligente de contatos</h2><p>Selecione .VCF ou .CSV. Nomes e números são lidos antes de salvar. Duplicados e inválidos ficam desmarcados.</p><div class="field"><input id="importFile" type="file" accept=".vcf,.csv,text/vcard,text/csv"></div><div class="grid2"><div class="field"><label>Grupo de destino</label><select id="importGroup">${groups.map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Tags</label><input id="importTags" placeholder="importação agosto"></div></div><div id="importPreview"></div><div class="actions"><button onclick="markImport(true)">Marcar válidos</button><button onclick="markImport(false)">Desmarcar todos</button><button class="primary" onclick="saveImport()">Salvar selecionados</button></div>`);$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();const raw=f.name.toLowerCase().endsWith('.vcf')?parseVCF(text):parseCSV(text);const existing=new Set(contacts.map(c=>c.phone));const seen=new Set();_import=raw.map((x,i)=>{let p=String(x.phone||'').replace(/\D/g,'');if(!p.startsWith('55')&&(p.length===10||p.length===11))p='55'+p;const valid=/^55\d{10,11}$/.test(p),dup=existing.has(p)||seen.has(p);seen.add(p);return{idx:i,name:x.name||'SEM NOME',phone:p,valid,duplicate:dup,selected:valid&&!dup}});renderImport()}}
function renderImport(){const good=_import.filter(x=>x.valid&&!x.duplicate).length,dup=_import.filter(x=>x.duplicate).length,bad=_import.filter(x=>!x.valid).length;$('#importPreview').innerHTML=`<p><span class="status ok">Válidos ${good}</span> <span class="status warn">Duplicados ${dup}</span> <span class="status bad">Inválidos ${bad}</span></p><div class="import-list">${_import.map((x,i)=>`<label class="import-item"><input type="checkbox" ${x.selected?'checked':''} ${!x.valid||x.duplicate?'disabled':''} onchange="_import[${i}].selected=this.checked"><div><b>${esc(x.name)}</b> ${x.duplicate?'<span class="status warn">duplicado</span>':''} ${!x.valid?'<span class="status bad">inválido</span>':''}<br>${esc(x.phone)}</div></label>`).join('')}</div>`}
function markImport(v){_import.forEach(x=>x.selected=v&&x.valid&&!x.duplicate);renderImport()}
async function saveImport(){try{const selected=_import.filter(x=>x.selected);if(!selected.length)return toast('Nenhum contato selecionado.');let ok=0,fail=0;for(const x of selected){try{await api('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:x.name,phone:x.phone,group_name:$('#importGroup').value,tags:$('#importTags').value,origin:'IMPORTAÇÃO',status:'ATIVO'})});ok++}catch{fail++}}closeModal();toast(`Importação concluída: ${ok} salvo(s), ${fail} falha(s).`);loadContacts()}catch(e){toast(e.message)}}

async function loadCampaigns(){try{campaigns=await api('/api/campaigns');renderCampaigns()}catch(e){toast(e.message)}}
function pct(a,b){return b?Math.round(a/b*100):0}
function renderCampaigns(){const el=$('#campaignList');el.innerHTML=campaigns.map(c=>`<div class="campaign"><h2>${esc(c.name)}</h2><p>Primeiro envio: ${fmt(c.start_at)} • Código ${esc(c.short_code)} • <span class="status ${c.status==='ATIVA'?'ok':c.status==='RASCUNHO'?'warn':''}">${esc(c.status)}</span></p><div class="progress"><i style="width:${pct(c.stats.sent+c.stats.failed+c.stats.canceled,c.stats.total)}%"></i></div><div class="stats"><div><strong>${c.stats.total}</strong>Total</div><div><strong>${c.stats.queue}</strong>Fila</div><div><strong>${c.stats.sent}</strong>Enviadas</div><div><strong>${c.stats.delivered}</strong>Entregues</div><div><strong>${c.stats.read}</strong>Lidas</div><div><strong>${c.stats.failed}</strong>Falhas</div></div><div class="actions"><button onclick="campaignDetails('${c.id}')">Detalhes</button>${['RASCUNHO','ATIVA'].includes(c.status)?`<button onclick="openCampaign('${c.id}')">Editar</button>`:''}${c.status==='RASCUNHO'?`<button class="primary" onclick="activateCampaign('${c.id}')">Ativar</button>`:''}${c.status==='ATIVA'?`<button class="danger" onclick="cancelCampaign('${c.id}')">Cancelar</button>`:''}<button onclick="duplicateCampaign('${c.id}')">Duplicar</button><button class="danger" onclick="deleteCampaign('${c.id}')">Excluir</button></div></div>`).join('')||'<div class="empty">Nenhuma campanha.</div>'}
async function openCampaign(id=''){if(!contacts.length||!groups.length)await Promise.all([loadGroups(),api('/api/contacts').then(x=>contacts=x)]);let c=null;if(id)c=await api(`/api/campaigns/${id}`);_steps=(c?.steps||[{delay_minutes:0,message:'',cta_enabled:true}]).map(x=>({...x}));showModal(`<h2>${id?'Editar':'Nova'} campanha</h2><div class="grid2"><div class="field"><label>Nome da campanha</label><input id="campName" value="${esc(c?.name||'')}"></div><div class="field"><label>Preço do bilhete</label><input id="campPrice" type="number" step=".01" value="${c?.unit_price||3}"></div><div class="field"><label>Primeiro envio</label><input id="campStart" type="datetime-local"></div><div class="field"><label>Público</label><select id="targetMode" onchange="targetChanged()"><option value="all">Todos os contatos ativos</option><option value="group">Um grupo</option><option value="selected">Selecionar contatos individualmente</option></select></div></div><div id="targetExtra"></div><div class="grid2"><label class="check"><input id="stopReply" type="checkbox" ${c?.stop_on_reply===false?'':'checked'}> Parar próximos lembretes quando responder</label><label class="check"><input id="stopOrder" type="checkbox" ${c?.stop_on_order===false?'':'checked'}> Parar próximos lembretes quando iniciar pedido</label></div><div id="stepsWrap"></div><button onclick="_steps.push({delay_minutes:60,message:'',cta_enabled:true});renderSteps()">+ Adicionar lembrete</button><div class="actions"><button class="primary" onclick="saveCampaign('${id}')">Salvar campanha</button></div>`);const local=c?.start_at?new Date(c.start_at):new Date(Date.now()+10*60000);$('#campStart').value=new Date(local.getTime()-local.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#targetMode').value=c?.target_mode||'all';targetChanged(c);renderSteps()}
function targetChanged(c=null){const m=$('#targetMode').value;if(m==='group')$('#targetExtra').innerHTML=`<div class="field"><label>Grupo</label><select id="targetGroup">${groups.map(g=>`<option ${g.name===c?.target_group?'selected':''}>${esc(g.name)}</option>`).join('')}</select></div>`;else if(m==='selected'){const s=new Set(c?.selected_contact_ids||[]);$('#targetExtra').innerHTML=`<div class="import-list">${contacts.filter(x=>x.status==='ATIVO'&&!x.opted_out).map(x=>`<label class="import-item"><input class="targetContact" type="checkbox" value="${x.id}" ${s.has(x.id)?'checked':''}><div><b>${esc(x.name)}</b><br>${esc(x.phone)} • ${esc(x.group_name)}</div></label>`).join('')}</div>`}else $('#targetExtra').innerHTML=''}
function renderSteps(){$('#stepsWrap').innerHTML=_steps.map((s,i)=>`<div class="stepbox"><h3>Mensagem ${i+1}</h3>${i?`<div class="field"><label>Enviar após a anterior (minutos)</label><input type="number" min="1" value="${s.delay_minutes||1}" onchange="_steps[${i}].delay_minutes=Number(this.value)"></div>`:''}<div class="field"><label>Texto</label><textarea onchange="_steps[${i}].message=this.value">${esc(s.message||'')}</textarea></div><div class="field"><label>Imagem (opcional)</label><input type="file" accept="image/*" onchange="stepImage(${i},this.files[0])">${s.image_data_url?`<img class="preview-img" src="${s.image_data_url}"><button class="danger" onclick="_steps[${i}].image_data_url=null;_steps[${i}].image_name=null;renderSteps()">Remover imagem</button>`:''}</div><label class="check"><input type="checkbox" ${s.cta_enabled!==false?'checked':''} onchange="_steps[${i}].cta_enabled=this.checked"> Adicionar link “🛒 PEDIR AGORA”</label>${i?`<button class="danger" onclick="_steps.splice(${i},1);renderSteps()">Remover etapa</button>`:''}</div>`).join('')}
function stepImage(i,f){if(!f)return;if(f.size>8*1024*1024)return toast('Imagem maior que 8 MB.');const r=new FileReader();r.onload=()=>{_steps[i].image_data_url=r.result;_steps[i].image_name=f.name;renderSteps()};r.readAsDataURL(f)}
async function saveCampaign(id){try{const start=$('#campStart').value;if(!start)return toast('Informe o primeiro envio.');if(_steps.some(s=>!String(s.message||'').trim()&&!s.image_data_url))return toast('Cada etapa precisa de texto ou imagem.');const b={name:$('#campName').value,unit_price:Number($('#campPrice').value||3),start_at:new Date(start).toISOString(),target_mode:$('#targetMode').value,target_group:$('#targetGroup')?.value||null,selected_contact_ids:$$('.targetContact:checked').map(x=>x.value),stop_on_reply:$('#stopReply').checked,stop_on_order:$('#stopOrder').checked,steps:_steps};await api(id?`/api/campaigns/${id}`:'/api/campaigns',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();toast('Campanha salva. Nenhuma mensagem foi enviada.');loadCampaigns()}catch(e){toast(e.message)}}
async function activateCampaign(id){if(!confirm('Ativar campanha? Nenhuma mensagem será enviada antes do horário programado.'))return;try{const r=await api(`/api/campaigns/${id}/activate`,{method:'POST'});toast(`Ativada: ${r.contacts} contatos / ${r.deliveries} envios na fila.`);loadCampaigns()}catch(e){toast(e.message)}}
async function cancelCampaign(id){if(!confirm('Cancelar envios ainda pendentes?'))return;try{await api(`/api/campaigns/${id}/cancel`,{method:'POST'});loadCampaigns()}catch(e){toast(e.message)}}
async function duplicateCampaign(id){try{await api(`/api/campaigns/${id}/duplicate`,{method:'POST'});toast('Campanha duplicada como rascunho.');loadCampaigns()}catch(e){toast(e.message)}}
async function deleteCampaign(id){if(!confirm('Excluir campanha e histórico de fila dessa campanha?'))return;try{await api(`/api/campaigns/${id}`,{method:'DELETE'});loadCampaigns()}catch(e){toast(e.message)}}
async function campaignDetails(id){try{const c=await api(`/api/campaigns/${id}`);showModal(`<h2>${esc(c.name)}</h2><p><span class="status">${esc(c.status)}</span> • primeiro envio ${fmt(c.start_at)} • código ${esc(c.short_code)}</p>${c.steps.map(s=>`<div class="stepbox"><b>Etapa ${s.step_index}${s.step_index>1?' • após '+s.delay_minutes+' min':''}</b><p>${esc(s.message)}</p>${s.image_data_url?`<img class="preview-img" src="${s.image_data_url}">`:''}<p>${s.cta_enabled?'🛒 CTA de compra ativado':''}</p></div>`).join('')}<h3>Fila por destinatário</h3>${c.deliveries.map(d=>`<div class="delivery"><b>${esc(d.phone)} • etapa ${d.step_index}</b> • <span class="status">${esc(d.status)}</span><br>${fmt(d.scheduled_at)}${d.error_text?`<br><small>${esc(d.error_text)}</small>`:''}</div>`).join('')||'<div class="empty">Fila ainda não criada.</div>'}`)}catch(e){toast(e.message)}}

async function loadExecution(){try{campaigns=await api('/api/campaigns');$('#executionList').innerHTML=campaigns.filter(c=>c.status!=='RASCUNHO').map(c=>`<div class="campaign"><h2>${esc(c.name)}</h2><p>${esc(c.status)} • primeiro envio ${fmt(c.start_at)}</p><div class="stats"><div><strong>${c.stats.queue}</strong>Na fila</div><div><strong>${c.stats.sent}</strong>Enviadas</div><div><strong>${c.stats.delivered}</strong>Entregues</div><div><strong>${c.stats.read}</strong>Lidas</div><div><strong>${c.stats.failed}</strong>Falhas</div><div><strong>${c.stats.canceled}</strong>Canceladas</div></div><button onclick="campaignDetails('${c.id}')">Abrir fila</button></div>`).join('')||'<div class="empty">Nenhuma execução.</div>'}catch(e){toast(e.message)}}
async function processNow(){try{await api('/api/queue/process',{method:'POST'});toast('Fila processada.');loadExecution()}catch(e){toast(e.message)}}

async function loadReturns(){try{messages=await api('/api/messages');renderReturns()}catch(e){toast(e.message)}}
function renderReturns(){const q=($('#returnSearch')?.value||'').toLowerCase(),m=new Map();for(const x of messages)if(!m.has(x.phone))m.set(x.phone,x);const l=[...m.values()].filter(x=>!q||[x.phone,x.body].join(' ').toLowerCase().includes(q));$('#returnsList').innerHTML=l.map(x=>`<div class="return-card"><h2>${esc(x.phone)}</h2><p>${fmt(x.created_at)}</p><div class="panel">${esc(x.body||'[mídia recebida]')}</div><a target="_blank" rel="noopener" href="https://wa.me/${esc(x.phone)}"><button>Abrir WhatsApp</button></a></div>`).join('')||'<div class="empty">Nenhum retorno.</div>'}

async function loadPurchases(){try{orders=await api('/api/orders');renderPurchases()}catch(e){toast(e.message)}}
function renderPurchases(){const f=$('#orderFilter')?.value||'',l=orders.filter(o=>!f||o.status===f);$('#purchasesList').innerHTML=l.map(o=>`<div class="order"><h2>${esc(o.code)}</h2><p>${esc(o.customer_name||o.phone)} • ${o.quantity||'-'} bilhete(s) • ${money(o.total_amount)}</p><p><span class="status ${o.status==='CONCLUIDO'?'ok':o.status==='COMPROVANTE_RECEBIDO'?'warn':''}">${esc(o.status)}</span> • ${fmt(o.updated_at)}</p><div class="actions">${o.status==='COMPROVANTE_RECEBIDO'?`<button class="primary" onclick="confirmPayment('${o.id}')">Confirmar pagamento</button>`:''}${o.status==='PAGAMENTO_CONFIRMADO'?`<button class="primary" onclick="completeOrder('${o.id}')">Concluir venda</button>`:''}${!['CONCLUIDO','CANCELADO'].includes(o.status)?`<button class="danger" onclick="cancelOrder('${o.id}')">Cancelar</button>`:''}<a href="https://wa.me/${esc(o.phone)}" target="_blank"><button>Abrir cliente</button></a></div></div>`).join('')||'<div class="empty">Nenhum pedido.</div>'}
async function confirmPayment(id){if(!confirm('Confirma que o PIX foi localizado?'))return;try{await api(`/api/orders/${id}/confirm-payment`,{method:'POST'});toast('Pagamento confirmado e cliente avisado.');loadPurchases()}catch(e){toast(e.message)}}
async function completeOrder(id){if(!confirm('Concluir venda e enviar mensagem final?'))return;try{await api(`/api/orders/${id}/complete`,{method:'POST'});toast('Compra concluída.');loadPurchases()}catch(e){toast(e.message)}}
async function cancelOrder(id){if(!confirm('Cancelar este pedido?'))return;try{await api(`/api/orders/${id}/cancel`,{method:'POST'});loadPurchases()}catch(e){toast(e.message)}}

async function loadSettings(){try{const [s,c]=await Promise.all([api('/api/status'),api('/api/settings')]);$('#waPanel').innerHTML=s.connected?`<p><span class="status ok">Conectado • ${esc(s.number||'')}</span></p>`:`${s.qrDataUrl?`<img class="preview-img" style="max-width:300px" src="${s.qrDataUrl}">`:'<p><span class="status warn">Desconectado</span></p>'}${s.lastError?`<p>${esc(s.lastError)}</p>`:''}`;$('#botEnabled').checked=!!c.bot_enabled;$('#pixKey').value=c.pix_key||'';$('#pixName').value=c.pix_name||'';$('#officeWA').value=c.office_whatsapp||'';$('#defaultPrice').value=c.default_unit_price||3;$('#triggerWords').value=c.trigger_words||'';$('#handoffWords').value=c.handoff_words||'';$('#optoutWords').value=c.optout_words||'';$('#orderPrompt').value=c.order_prompt||'';$('#fallbackMessage').value=c.fallback_message||'';$('#proofMessage').value=c.proof_received_message||'';$('#finalMessage').value=c.final_message||'';$('#botSavedInfo').innerHTML=c.saved_at?`<p><span class="status ok">Última configuração: ${fmt(c.saved_at)}</span></p>`:''}catch(e){toast(e.message)}}
async function connectWA(){try{await api('/api/whatsapp/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});toast('Conexão solicitada.');setTimeout(loadSettings,1500)}catch(e){toast(e.message)}}
async function logoutWA(){if(!confirm('Desconectar WhatsApp?'))return;try{await api('/api/whatsapp/logout',{method:'POST'});loadSettings()}catch(e){toast(e.message)}}
async function testWA(){try{await api('/api/whatsapp/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:$('#testTo').value,text:$('#testText').value})});toast('Teste enviado.')}catch(e){toast(e.message)}}
async function saveSettings(){try{const b={bot_enabled:$('#botEnabled').checked,pix_key:$('#pixKey').value,pix_name:$('#pixName').value,office_whatsapp:$('#officeWA').value,default_unit_price:Number($('#defaultPrice').value||3),trigger_words:$('#triggerWords').value,handoff_words:$('#handoffWords').value,optout_words:$('#optoutWords').value,order_prompt:$('#orderPrompt').value,fallback_message:$('#fallbackMessage').value,proof_received_message:$('#proofMessage').value,final_message:$('#finalMessage').value};const r=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});$('#botSavedInfo').innerHTML=`<p><span class="status ok">Bot salvo em ${fmt(r.saved_at)}</span></p>`;toast('Bot salvo com sucesso.')}catch(e){toast(e.message)}}
async function testBot(){try{await api('/api/bot/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:$('#testTo').value})});toast('Teste do bot enviado.')}catch(e){toast(e.message)}}
async function runDiagnostics(){try{const d=await api('/api/diagnostics');const rows=Object.entries(d.tables||{}).map(([k,v])=>`<div class="delivery"><b>${esc(k)}</b> — ${v===true?'<span class="status ok">OK</span>':`<span class="status bad">${esc(v)}</span>`}</div>`).join('');showModal(`<h2>Diagnóstico V10 FINAL</h2><p>Supabase: <span class="status ${d.supabase?'ok':'bad'}">${d.supabase?'OK':'ERRO'}</span> • WhatsApp: <span class="status ${d.whatsapp?'ok':'warn'}">${d.whatsapp?'CONECTADO':'DESCONECTADO'}</span></p>${rows}`)}catch(e){toast(e.message)}}

if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});refreshStatus();loadHome();setInterval(refreshStatus,15000);
