(()=>{
 const TOKEN_KEY='rds:operatorToken', CPF_KEY='rds:operatorCpf', REMEMBER_KEY='rds:rememberAccess';
 const rawFetch=window.fetch.bind(window);
 let appOpened=false, sessionExpiredShown=false;
 const getToken=()=>localStorage.getItem(TOKEN_KEY)||sessionStorage.getItem(TOKEN_KEY)||'';
 const getCpf=()=>localStorage.getItem(CPF_KEY)||sessionStorage.getItem(CPF_KEY)||'';
 function clearAuth(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(CPF_KEY);sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(CPF_KEY)}
 function saveAuth(token,cpf,remember){clearAuth();const s=remember?localStorage:sessionStorage;s.setItem(TOKEN_KEY,token||'');s.setItem(CPF_KEY,cpf||'');localStorage.setItem(REMEMBER_KEY,remember?'1':'0')}
 window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||'');const headers=new Headers(init.headers||{});const token=getToken();if(token&&url.startsWith('/api/'))headers.set('Authorization','Bearer '+token);const r=await rawFetch(input,{...init,headers});if(r.status===401&&url.startsWith('/api/')&&!url.includes('/v1026/auth/')){clearAuth();if(appOpened&&!sessionExpiredShown){sessionExpiredShown=true;showLogin('Sua sessão expirou. Entre novamente.')}}return r};
 const css=document.createElement('style');css.textContent=`#rdsAuthGate{position:fixed;inset:0;z-index:9999;background:linear-gradient(145deg,#061d3f,#0c4f9c);display:grid;place-items:center;padding:18px;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.rds-auth-card{width:min(430px,94vw);background:#fff;border-radius:24px;padding:28px;box-shadow:0 28px 90px #00152f66}.rds-auth-brand{display:flex;align-items:center;gap:13px;margin-bottom:20px}.rds-auth-mark{width:54px;height:54px;border-radius:16px;background:linear-gradient(145deg,#0a4082,#1674d1);color:#fff;display:grid;place-items:center;font-weight:900}.rds-auth-card h1{margin:0;color:#12335c;font-size:25px}.rds-auth-card p{color:#6f7e94;line-height:1.45}.rds-auth-card label{display:block;font-size:12px;font-weight:800;color:#42566e;margin:12px 0 6px}.rds-auth-card input[type=text],.rds-auth-card input[type=password]{width:100%;box-sizing:border-box;border:1px solid #ccd8e7;border-radius:12px;padding:12px;font:inherit}.rds-auth-card button{width:100%;border:0;border-radius:12px;padding:12px 14px;background:linear-gradient(135deg,#0d55a5,#1674d1);color:#fff;font-weight:900;margin-top:14px;font:inherit}.rds-auth-link{background:transparent!important;color:#0d55a5!important;border:1px solid #ccd8e7!important}.rds-auth-msg{margin-top:10px;color:#a32933;font-size:13px;min-height:18px}.rds-auth-sub{font-size:12px;color:#7b889a}.rds-auth-remember{display:flex!important;align-items:center;gap:9px;margin:14px 0 2px!important;font-weight:700!important;color:#52657b!important}.rds-auth-remember input{width:auto!important}.rds-auth-help{font-size:11px;color:#7b889a;margin-top:6px}.rds-logout{margin-left:8px;border:1px solid #ccd8e7;background:#fff;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:800;color:#31506f}`;document.head.appendChild(css);
 function gate(html){let g=document.querySelector('#rdsAuthGate');if(!g){g=document.createElement('div');g.id='rdsAuthGate';document.body.appendChild(g)}g.innerHTML=html;document.querySelector('.app-shell')?.style.setProperty('visibility','hidden');document.querySelector('#mobileNav')?.style.setProperty('visibility','hidden')}
 function loading(){gate(`<div class=rds-auth-card><div class=rds-auth-brand><div class=rds-auth-mark>RDS</div><div><h1>Canal de Vendas</h1><div class=rds-auth-sub>Verificando acesso...</div></div></div></div>`)}
 function openApp(cpf){document.querySelector('#rdsAuthGate')?.remove();document.querySelector('.app-shell')?.style.removeProperty('visibility');document.querySelector('#mobileNav')?.style.removeProperty('visibility');const top=document.querySelector('.top-actions');if(top&&!document.querySelector('#rdsLogout'))top.insertAdjacentHTML('beforeend','<button id="rdsLogout" class="rds-logout">Sair</button>');document.querySelector('#rdsLogout')?.addEventListener('click',logout);appOpened=true;sessionExpiredShown=false}
 async function json(url,opt={}){const r=await rawFetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Falha');return d}
 async function status(){const token=getToken();return json('/api/v1026/auth/status',{headers:token?{Authorization:'Bearer '+token}:{}})}
 function cpfMask(v){const d=String(v||'').replace(/\D/g,'').slice(0,11);return d.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')}
 function card(title,text,button,register=false){const remembered=localStorage.getItem(REMEMBER_KEY)!=='0';return `<div class=rds-auth-card><div class=rds-auth-brand><div class=rds-auth-mark>RDS</div><div><h1>Canal de Vendas</h1><div class=rds-auth-sub>Acesso do operador</div></div></div><h2 style="margin:0;color:#12335c">${title}</h2><p>${text}</p><label>CPF</label><input id=rdsCpf type=text inputmode=numeric autocomplete=username placeholder="000.000.000-00" value="${register?'':cpfMask(getCpf())}"><label>Senha</label><input id=rdsPass type=password autocomplete="${register?'new-password':'current-password'}" placeholder="Mínimo 8 caracteres">${register?'':`<label class=rds-auth-remember><input id=rdsRemember type=checkbox ${remembered?'checked':''}> Manter meu acesso neste aparelho</label><div class=rds-auth-help>Com esta opção, o acesso permanece neste aparelho por até 30 dias. A senha continua protegida pelo gerenciador seguro do navegador.</div>`}<button id=rdsEnter>${button}</button><div id=rdsAuthMsg class=rds-auth-msg></div>${register?'<button id=rdsBack class=rds-auth-link>Voltar para entrar</button>':'<button id=rdsRegister class=rds-auth-link>Cadastro</button>'}</div>`}
 function bindCpf(){const c=document.querySelector('#rdsCpf');c?.addEventListener('input',()=>c.value=cpfMask(c.value))}
 function showLogin(msg=''){appOpened=false;sessionExpiredShown=false;gate(card('Entrar','Entre com seu CPF e senha.','Entrar'));bindCpf();document.querySelector('#rdsEnter').onclick=login;document.querySelector('#rdsRegister').onclick=showRegister;document.querySelector('#rdsPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});if(msg)document.querySelector('#rdsAuthMsg').textContent=msg}
 function showRegister(){appOpened=false;gate(card('Cadastro','Cadastre seu CPF e uma senha para acessar o aplicativo. O CPF será seu usuário único.','Cadastrar',true));bindCpf();document.querySelector('#rdsEnter').onclick=register;document.querySelector('#rdsBack').onclick=()=>showLogin();document.querySelector('#rdsPass').addEventListener('keydown',e=>{if(e.key==='Enter')register()})}
 async function register(){try{const cpf=document.querySelector('#rdsCpf').value.replace(/\D/g,''),password=document.querySelector('#rdsPass').value;const d=await json('/api/v1026/auth/register',{method:'POST',body:JSON.stringify({cpf,password})});saveAuth(d.token,d.cpf||cpf,true);location.reload()}catch(e){document.querySelector('#rdsAuthMsg').textContent=e.message}}
 async function login(){try{const cpf=document.querySelector('#rdsCpf').value.replace(/\D/g,''),password=document.querySelector('#rdsPass').value,remember=!!document.querySelector('#rdsRemember')?.checked;const d=await json('/api/v1026/auth/login',{method:'POST',body:JSON.stringify({cpf,password,remember})});saveAuth(d.token,d.cpf||cpf,remember);location.reload()}catch(e){document.querySelector('#rdsAuthMsg').textContent=e.message}}
 async function logout(){try{await fetch('/api/v1026/auth/logout',{method:'POST'})}catch{}clearAuth();appOpened=false;showLogin()}
 async function boot(){loading();try{const s=await status();if(s.authenticated)openApp(s.cpf);else if(s.configured)showLogin();else showRegister()}catch{showLogin('Não foi possível validar a sessão. Tente novamente.')}}
 loading();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
