-- PROJETO ZAP V5.7.1 - MIGRAÇÃO ÚNICA E IDEMPOTENTE
-- Pode executar mais de uma vez. Não apaga campanhas, contatos ou histórico.
create extension if not exists pgcrypto;

create table if not exists public.zap_auth(id text primary key,value jsonb not null,updated_at timestamptz not null default now());

create table if not exists public.pz_settings(
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists pz_settings_key_idx on public.pz_settings(key);

create table if not exists public.pz_contacts(
  id uuid primary key default gen_random_uuid(), phone text not null unique, name text, group_name text default 'NOVOS', status text default 'ATIVO', opt_in boolean default true, opt_out boolean default false, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.pz_contacts add column if not exists group_name text default 'NOVOS';
alter table public.pz_contacts add column if not exists status text default 'ATIVO';
alter table public.pz_contacts add column if not exists opt_in boolean default true;
alter table public.pz_contacts add column if not exists opt_out boolean default false;
alter table public.pz_contacts add column if not exists updated_at timestamptz default now();
create unique index if not exists pz_contacts_phone_uq on public.pz_contacts(phone);

create table if not exists public.pz_campaigns(
  id uuid primary key default gen_random_uuid(), name text not null, messages jsonb not null default '[]'::jsonb, image_url text, schedule_at timestamptz, status text default 'AGENDADA', interval_min integer default 6, interval_max integer default 12, retry_enabled boolean default false, retry_hours numeric default 24, max_attempts integer default 1, unit_price numeric(12,2) default 0, auto_bot_enabled boolean default true, started_at timestamptz, finished_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.pz_campaigns add column if not exists messages jsonb not null default '[]'::jsonb;
alter table public.pz_campaigns add column if not exists image_url text;
alter table public.pz_campaigns add column if not exists schedule_at timestamptz;
alter table public.pz_campaigns add column if not exists status text default 'AGENDADA';
alter table public.pz_campaigns add column if not exists interval_min integer default 6;
alter table public.pz_campaigns add column if not exists interval_max integer default 12;
alter table public.pz_campaigns add column if not exists retry_enabled boolean default false;
alter table public.pz_campaigns add column if not exists retry_hours numeric default 24;
alter table public.pz_campaigns add column if not exists max_attempts integer default 1;
alter table public.pz_campaigns add column if not exists unit_price numeric(12,2) default 0;
alter table public.pz_campaigns add column if not exists auto_bot_enabled boolean default true;
alter table public.pz_campaigns add column if not exists started_at timestamptz;
alter table public.pz_campaigns add column if not exists finished_at timestamptz;
alter table public.pz_campaigns add column if not exists updated_at timestamptz default now();

create table if not exists public.pz_recipients(
  id uuid primary key default gen_random_uuid(), campaign_id uuid, contact_id uuid, phone text not null, name text, status text default 'PENDENTE', selected_message integer default 0, attempt_count integer default 0, max_attempts integer default 1, next_action_at timestamptz, meta_message_id text, sent_at timestamptz, responded_at timestamptz, purchase_at timestamptz, possible_payment_at timestamptz, last_inbound_preview text, last_inbound_type text, error_text text, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.pz_recipients add column if not exists selected_message integer default 0;
alter table public.pz_recipients add column if not exists attempt_count integer default 0;
alter table public.pz_recipients add column if not exists max_attempts integer default 1;
alter table public.pz_recipients add column if not exists next_action_at timestamptz;
alter table public.pz_recipients add column if not exists meta_message_id text;
alter table public.pz_recipients add column if not exists sent_at timestamptz;
alter table public.pz_recipients add column if not exists responded_at timestamptz;
alter table public.pz_recipients add column if not exists purchase_at timestamptz;
alter table public.pz_recipients add column if not exists possible_payment_at timestamptz;
alter table public.pz_recipients add column if not exists last_inbound_preview text;
alter table public.pz_recipients add column if not exists last_inbound_type text;
alter table public.pz_recipients add column if not exists error_text text;
alter table public.pz_recipients add column if not exists updated_at timestamptz default now();
create index if not exists pz_recipients_campaign_idx on public.pz_recipients(campaign_id);
create index if not exists pz_recipients_phone_idx on public.pz_recipients(phone);
create index if not exists pz_recipients_status_idx on public.pz_recipients(status,next_action_at);

create table if not exists public.pz_messages(
  id uuid primary key default gen_random_uuid(), phone text, contact_id uuid, campaign_id uuid, recipient_id uuid, meta_message_id text, direction text, message_type text, body text, status text, raw_payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
alter table public.pz_messages add column if not exists contact_id uuid;
alter table public.pz_messages add column if not exists campaign_id uuid;
alter table public.pz_messages add column if not exists recipient_id uuid;
alter table public.pz_messages add column if not exists meta_message_id text;
alter table public.pz_messages add column if not exists direction text;
alter table public.pz_messages add column if not exists message_type text;
alter table public.pz_messages add column if not exists body text;
alter table public.pz_messages add column if not exists status text;
alter table public.pz_messages add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.pz_messages add column if not exists created_at timestamptz default now();
-- Remove duplicados antigos antes de criar unicidade.
delete from public.pz_messages a using public.pz_messages b where a.ctid < b.ctid and a.meta_message_id is not null and a.meta_message_id=b.meta_message_id;
create unique index if not exists pz_messages_meta_unique on public.pz_messages(meta_message_id) where meta_message_id is not null;

create table if not exists public.pz_orders(
  id uuid primary key default gen_random_uuid(), recipient_id uuid, campaign_id uuid, contact_id uuid, phone text, name text, quantity integer default 0, unit_price numeric(12,2) default 0, total_amount numeric(12,2) default 0, contact_phone text, status text default 'COLETANDO_DADOS', created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.pz_orders add column if not exists recipient_id uuid;
alter table public.pz_orders add column if not exists campaign_id uuid;
alter table public.pz_orders add column if not exists contact_id uuid;
alter table public.pz_orders add column if not exists phone text;
alter table public.pz_orders add column if not exists name text;
alter table public.pz_orders add column if not exists quantity integer default 0;
alter table public.pz_orders add column if not exists unit_price numeric(12,2) default 0;
alter table public.pz_orders add column if not exists total_amount numeric(12,2) default 0;
alter table public.pz_orders add column if not exists contact_phone text;
alter table public.pz_orders add column if not exists status text default 'COLETANDO_DADOS';
alter table public.pz_orders add column if not exists updated_at timestamptz default now();

create table if not exists public.pz_purchases(
  id uuid primary key default gen_random_uuid(), contact_id uuid, campaign_id uuid, recipient_id uuid, phone text, name text, source text, notes text, created_at timestamptz default now()
);

create table if not exists public.pz_jid_map(
  phone text primary key, lid_jid text unique, updated_at timestamptz default now()
);

insert into public.pz_settings(key,value)
values('bot','{"enabled":true,"pix_key":"","pix_name":"REINO DA SORTE","trigger_keywords":["quero","comprar","compra","bilhete","bilhetes","pedido","reservar","garantir"],"order_prompt":"Para fazer seu pedido, responda preenchendo:\nNome:\nQuantidade:\nContato:","thank_you_message":"🍀 A Reino da Sorte agradece a sua compra. Boa sorte! 🍀"}'::jsonb)
on conflict(key) do nothing;

select 'PROJETO ZAP V5.7.1 - BANCO ALINHADO COM SUCESSO' as resultado;
