const express=require('express');
const crypto=require('crypto');
const pino=require('pino');
const QRCode=require('qrcode');
const {default:makeWASocket,DisconnectReason,Browsers,initAuthCreds,BufferJSON,proto}=require('@whiskeysockets/baileys');

const app=express();
app.use(express.json({limit:'15mb'}));
app.use(express.urlencoded({extended:true,limit:'15mb'}));
app.use(express.static(__dirname));

const PORT=process.env.PORT||10000;
const SUPABASE_URL=String(process.env.SUPABASE_URL||'').replace(/\/+$/,'');
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_KEY||process.env.SUPABASE_ANON_KEY||'';
const CRON_SECRET=String(process.env.CRON_SECRET||'');
const STORAGE_BUCKET='projeto-zap-campanhas';
const TERMINAL=new Set(['COMPRA_REALIZADA','NAO_INTERESSADO','SEM_RESPOSTA','DESCADASTRADO']);
const PURCHASE_PHRASES=['pagamento confirmado','compra confirmada','obrigado pela compra','obrigada pela compra','agradecemos sua compra','compra realizada','pagamento recebido'];
const BOT_DEFAULT_TRIGGERS=['quero','comprar','compra','bilhete','bilhetes','pedido','reservar','garantir'];
const BOT_NEGATIVE=['não quero','nao quero','sem interesse','não tenho interesse','nao tenho interesse','pare','sair'];
let sock=null,connected=false,starting=false,qrDataUrl='',connectedNumber='',connectedName='',lastError='',lastConnectionAt=null,restartTimer=null,generation=0,runnerBusy=false;

const digits=v=>String(v||'').replace(/\D/g,'');
function normalizeBR(v){let n=digits(v);if(n.startsWith('00'))n=n.slice(2);if(!n.startsWith('55')&&(n.length===10||n.length===11))n='55'+n;return n}
const tail=v=>digits(v).slice(-11);
const nowIso=()=>new Date().toISOString();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const randomMs=(a,b)=>{a=Math.max(3,Number(a)||6);b=Math.max(a,Number(b)||12);return Math.floor((a+Math.random()*(b-a))*1000)};
const safeJson=v=>JSON.parse(JSON.stringify(v,BufferJSON.replacer));
const restoreJson=v=>JSON.parse(JSON.stringify(v),BufferJSON.reviver);
async function sb(path,opt={}){if(!SUPABASE_URL||!SUPABASE_KEY)throw new Error('Supabase não configurado no Render.');const r=await fetch(SUPABASE_URL+path,{...opt,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(opt.headers||{})}});const txt=await r.text();let data=null;try{data=txt?JSON.parse(txt):null}catch{data=txt}if(!r.ok)throw new Error(data?.message||data?.error||data?.details||`Supabase ${r.status}`);return data}
async function authRead(id){const x=await sb(`/rest/v1/zap_auth?select=value&id=eq.${encodeURIComponent(id)}&limit=1`);return x?.[0]?.value?restoreJson(x[0].value):null}
async function authWrite(id,value){await sb('/rest/v1/zap_auth?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id,value:safeJson(value),updated_at:nowIso()})})}
async function authDelete(id){await sb(`/rest/v1/zap_auth?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'})}
async function authClear(){await sb('/rest/v1/zap_auth?id=not.is.null',{method:'DELETE'})}
async function useSupabaseAuthState(){const creds=(await authRead('creds'))||initAuthCreds();return{state:{creds,keys:{get:async(type,ids)=>{const out={};await Promise.all(ids.map(async id=>{let v=await authRead(`${type}-${id}`);if(type==='app-state-sync-key'&&v)v=proto.Message.AppStateSyncKeyData.fromObject(v);out[id]=v}));return out},set:async data=>{const jobs=[];for(const cat of Object.keys(data||{}))for(const id of Object.keys(data[cat]||{})){const v=data[cat][id];jobs.push(v?authWrite(`${cat}-${id}`,v):authDelete(`${cat}-${id}`))}await Promise.all(jobs)}}},saveCreds:()=>authWrite('creds',creds)}}
async function closeSocket(clear=false){generation++;try{sock?.ws?.close?.()}catch{}sock=null;connected=false;starting=false;if(clear){connectedNumber='';connectedName='';qrDataUrl=''}}
function scheduleRestart(ms=1800){clearTimeout(restartTimer);restartTimer=setTimeout(()=>startWhatsApp(false).catch(e=>lastError=e.message),ms)}
async function startWhatsApp(force=false){if(starting)return;if(sock&&!force)return;starting=true;if(force)await closeSocket(false);const myGen=++generation;try{const {state,saveCreds}=await useSupabaseAuthState();sock=makeWASocket({auth:state,printQRInTerminal:false,logger:pino({level:'silent'}),browser:Browsers.ubuntu('Google Chrome'),markOnlineOnConnect:false,syncFullHistory:false,shouldSyncHistoryMessage:()=>false,generateHighQualityLinkPreview:false});const s=sock;s.ev.on('creds.update',saveCreds);s.ev.on('connection.update',async u=>{if(myGen!==generation)return;const {connection,lastDisconnect,qr}=u;if(qr){qrDataUrl=await QRCode.toDataURL(qr,{margin:2,width:440});connected=false;lastError=''}if(connection==='open'){connected=true;starting=false;qrDataUrl='';connectedNumber=digits(s.user?.id?.split(':')?.[0]||s.user?.id||'');connectedName=String(s.user?.name||s.user?.verifiedName||'Projeto Zap');lastConnectionAt=nowIso();lastError='';setTimeout(()=>runDueCampaigns().catch(()=>{}),1200)}if(connection==='close'){connected=false;starting=false;const code=Number(lastDisconnect?.error?.output?.statusCode||lastDisconnect?.error?.statusCode||0);const loggedOut=code===DisconnectReason.loggedOut||code===401;lastError=loggedOut?'Sessão encerrada no WhatsApp.':String(lastDisconnect?.error?.message||`Conexão encerrada (${code||'sem código'}).`);try{s?.ws?.close?.()}catch{}if(sock===s)sock=null;if(loggedOut){await authClear().catch(()=>{});connectedNumber='';connectedName='';qrDataUrl=''}else scheduleRestart(code===515?900:2200)}});s.ev.on('lid-mapping.update',async mapping=>{try{const items=Array.isArray(mapping)?mapping:[mapping];for(const x of items){if(x?.pn&&x?.lid)await saveJidMap(x.pn,x.lid)}}catch{}});s.ev.on('messages.upsert',async({messages})=>{for(const m of messages||[])if(m?.message)await processMessage(m).catch(e=>console.log('Mensagem:',e.message))})}catch(e){lastError=e.message;sock=null;connected=false;starting=false;scheduleRestart(3500);throw e}}
async function ensureConnected(timeout=25000){if(connected&&sock)return true;if(!starting&&!sock)await startWhatsApp(false).catch(()=>{});const end=Date.now()+timeout;while(Date.now()<end){if(connected&&sock)return true;await sleep(500)}return false}
function msgText(m){const x=m?.message||{};return String(x.conversation||x.extendedTextMessage?.text||x.imageMessage?.caption||x.videoMessage?.caption||x.documentMessage?.caption||'').trim()}
function msgType(m){const x=m?.message||{};if(x.imageMessage)return'image';if(x.documentMessage)return String(x.documentMessage?.mimetype||'').includes('pdf')?'pdf':'document';if(x.videoMessage)return'video';if(x.audioMessage)return'audio';return'text'}
const isPurchasePhrase=t=>PURCHASE_PHRASES.some(p=>String(t||'').toLowerCase().includes(p));
const lower=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const validBRPhone=n=>/^55\d{10,11}$/.test(normalizeBR(n));
function jidToPhone(jid){const s=String(jid||'');if(!s.endsWith('@s.whatsapp.net'))return'';const n=normalizeBR(s.split('@')[0]);return validBRPhone(n)?n:''}
async function saveJidMap(pn,lid){const phone=jidToPhone(pn)||normalizeBR(pn),lidJid=String(lid||'');if(!validBRPhone(phone)||!lidJid.endsWith('@lid'))return;await sb('/rest/v1/pz_jid_map?on_conflict=phone',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({phone,lid_jid:lidJid,updated_at:nowIso()})}).catch(()=>{})}
async function resolveMessageIdentity(m){
  const k=m?.key||{};
  const direct=[k.remoteJidAlt,k.participantPn,k.participantAlt,k.senderPn].map(jidToPhone).find(Boolean);
  if(direct){if(String(k.remoteJid||'').endsWith('@lid'))await saveJidMap(`${direct}@s.whatsapp.net`,k.remoteJid);return{phone:direct,source:'alt',jid:String(k.remoteJid||'')}}
  const remote=jidToPhone(k.remoteJid);if(remote)return{phone:remote,source:'pn',jid:String(k.remoteJid||'')};
  const lid=String(k.remoteJid||'');
  if(lid.endsWith('@lid')){
    try{const fn=sock?.signalRepository?.lidMapping?.getPNForLID;if(typeof fn==='function'){const pn=await fn.call(sock.signalRepository.lidMapping,lid);const p=jidToPhone(pn)||normalizeBR(pn);if(validBRPhone(p)){await saveJidMap(`${p}@s.whatsapp.net`,lid);return{phone:p,source:'signal',jid:lid}}}}catch{}
    try{const rows=await sb(`/rest/v1/pz_jid_map?lid_jid=eq.${encodeURIComponent(lid)}&select=phone&limit=1`);if(validBRPhone(rows?.[0]?.phone))return{phone:normalizeBR(rows[0].phone),source:'db',jid:lid}}catch{}
  }
  const stanza=String(m?.message?.extendedTextMessage?.contextInfo?.stanzaId||m?.message?.imageMessage?.contextInfo?.stanzaId||m?.message?.documentMessage?.contextInfo?.stanzaId||'');
  if(stanza){try{const rows=await sb(`/rest/v1/pz_recipients?meta_message_id=eq.${encodeURIComponent(stanza)}&select=phone&order=created_at.desc&limit=1`);if(validBRPhone(rows?.[0]?.phone))return{phone:normalizeBR(rows[0].phone),source:'quoted',jid:lid}}catch{}}
  return{phone:'',source:'unresolved',jid:lid};
}
async function getSettings(){const rows=await sb('/rest/v1/pz_settings?id=eq.main&select=*&limit=1').catch(()=>[]);return rows?.[0]||{bot_enabled:true,pix_key:'',pix_name:'REINO DA SORTE',trigger_keywords:BOT_DEFAULT_TRIGGERS,thank_you_message:'🍀 A Reino da Sorte agradece a sua compra. Boa sorte! 🍀',order_prompt:'Para fazer seu pedido, responda preenchendo:\nNome:\nQuantidade:\nContato:'}}
function isBuyIntent(text,settings){const t=lower(text);if(BOT_NEGATIVE.some(x=>t.includes(lower(x))))return false;const keys=Array.isArray(settings?.trigger_keywords)&&settings.trigger_keywords.length?settings.trigger_keywords:BOT_DEFAULT_TRIGGERS;return keys.some(k=>t.includes(lower(k)))}
function parseOrder(text,fallbackPhone){const lines=String(text||'').split(/\n|;/).map(s=>s.trim()).filter(Boolean);let name='',qty=0,contact='';for(const line of lines){let m=line.match(/^nome\s*[:\-]\s*(.+)$/i);if(m)name=m[1].trim();m=line.match(/^(quantidade|qtd|bilhetes?)\s*[:\-]\s*(\d{1,4})/i);if(m)qty=Number(m[2]);m=line.match(/^(contato|telefone|whatsapp)\s*[:\-]\s*(.+)$/i);if(m)contact=normalizeBR(m[2])}if(!qty){const q=String(text||'').match(/\b(\d{1,4})\s*(bilhete|bilhetes|unidade|unidades)\b/i);if(q)qty=Number(q[1])}if(!contact)contact=normalizeBR(fallbackPhone);return{name,qty,contact}}
async function getOrder(recipientId){const rows=await sb(`/rest/v1/pz_orders?recipient_id=eq.${encodeURIComponent(recipientId)}&select=*&order=created_at.desc&limit=1`).catch(()=>[]);return rows?.[0]||null}
async function upsertOrder(recipient,campaign,data={}){const existing=await getOrder(recipient.id),unit=Number(campaign?.unit_price||existing?.unit_price||0),qty=Math.max(0,Number(data.qty||existing?.quantity||0)),body={recipient_id:recipient.id,campaign_id:recipient.campaign_id,contact_id:recipient.contact_id||null,phone:recipient.phone,name:String(data.name||existing?.name||recipient.name||''),quantity:qty,unit_price:unit,total_amount:Number((qty*unit).toFixed(2)),contact_phone:normalizeBR(data.contact||existing?.contact_phone||recipient.phone),status:String(data.status||existing?.status||'COLETANDO_DADOS'),updated_at:nowIso()};if(existing){await sb(`/rest/v1/pz_orders?id=eq.${existing.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});return{...existing,...body}}const rows=await sb('/rest/v1/pz_orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});return rows?.[0]||body}
async function botSend(phone,text){if(!text)return;await sendText(phone,text);await sb('/rest/v1/pz_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({phone, direction:'OUT',message_type:'text',body:text,status:'sent',raw_payload:{source:'BOT'}})}).catch(()=>{})}
async function handleInboundBot(recipient,campaign,contact,text,type){const settings=await getSettings();if(!settings.bot_enabled||campaign?.auto_bot_enabled===false)return;const status=String(recipient.status||'');
  if(['image','pdf','document'].includes(type)&&['AGUARDANDO_PAGAMENTO','PEDIDO_CONFIRMADO'].includes(status)){
    await upsertOrder(recipient,campaign,{status:'COMPROVANTE_RECEBIDO'});await sb(`/rest/v1/pz_recipients?id=eq.${recipient.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'POSSIVEL_PAGAMENTO',possible_payment_at:nowIso(),last_inbound_preview:`[${type}] possível comprovante`,last_inbound_type:type,next_action_at:null,updated_at:nowIso()})});return;
  }
  if(type!=='text')return;
  if(['ENVIADA','ENTREGUE','LIDA','RESPONDEU','EM_NEGOCIACAO'].includes(status)&&isBuyIntent(text,settings)){
    await upsertOrder(recipient,campaign,{status:'AGUARDANDO_DADOS'});await sb(`/rest/v1/pz_recipients?id=eq.${recipient.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'AGUARDANDO_DADOS',responded_at:recipient.responded_at||nowIso(),last_inbound_preview:text,updated_at:nowIso()})});await botSend(recipient.phone,settings.order_prompt||'Para fazer seu pedido, responda preenchendo:\nNome:\nQuantidade:\nContato:');return;
  }
  if(status==='AGUARDANDO_DADOS'){
    const d=parseOrder(text,recipient.phone);if(!d.qty||d.qty<1){await botSend(recipient.phone,'Não consegui identificar a quantidade. Responda assim:\nNome: Seu nome\nQuantidade: 10\nContato: seu WhatsApp');return}
    const order=await upsertOrder(recipient,campaign,{...d,status:'AGUARDANDO_PAGAMENTO'});await sb(`/rest/v1/pz_recipients?id=eq.${recipient.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'AGUARDANDO_PAGAMENTO',last_inbound_preview:`Pedido: ${order.quantity} bilhete(s)`,updated_at:nowIso()})});const total=Number(order.total_amount||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let pix=`✅ Pedido recebido!\nNome: ${order.name||contact?.name||'Cliente'}\nQuantidade: ${order.quantity}\nTotal: ${total}`;if(settings.pix_key)pix+=`\n\nPIX: ${settings.pix_key}${settings.pix_name?`\nFavorecido: ${settings.pix_name}`:''}`;else pix+='\n\nAguarde a chave PIX do atendimento.';pix+='\n\nApós pagar, envie aqui a foto ou PDF do comprovante.';await botSend(recipient.phone,pix);return;
  }
}

async function findContact(phone){const rows=await sb(`/rest/v1/pz_contacts?select=*&phone=eq.${encodeURIComponent(normalizeBR(phone))}&limit=1`);return rows?.[0]||null}
async function upsertContact(phone,name=''){const n=normalizeBR(phone);let c=await findContact(n);if(c)return c;const rows=await sb('/rest/v1/pz_contacts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({phone:n,name:name||`Cliente ${n.slice(-4)}`,group_name:'NOVOS',status:'ATIVO',opt_in:true,opt_out:false})});return rows?.[0]||null}
async function latestRecipient(phone){const rows=await sb(`/rest/v1/pz_recipients?select=*&phone=eq.${encodeURIComponent(normalizeBR(phone))}&order=created_at.desc&limit=20`);return (rows||[]).find(r=>!TERMINAL.has(r.status))||null}
async function recordPurchase(recipient,source='MANUAL',notes=''){if(!recipient)return;await sb('/rest/v1/pz_purchases',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({contact_id:recipient.contact_id||null,campaign_id:recipient.campaign_id||null,recipient_id:recipient.id,phone:recipient.phone,name:recipient.name||'',source,notes})}).catch(()=>{});await sb(`/rest/v1/pz_recipients?id=eq.${recipient.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'COMPRA_REALIZADA',purchase_at:nowIso(),next_action_at:null,updated_at:nowIso()})})}
async function processMessage(m){
  const rawJid=String(m.key?.remoteJid||'');if(!rawJid||rawJid.endsWith('@g.us')||rawJid==='status@broadcast'||rawJid.endsWith('@broadcast'))return;
  const fromMe=Boolean(m.key?.fromMe),text=msgText(m),type=msgType(m),identity=await resolveMessageIdentity(m);let phone=identity.phone;
  if(!phone){console.log('Mensagem sem PN resolvido:',rawJid,String(m.key?.remoteJidAlt||''));return}
  const duplicate=await sb(`/rest/v1/pz_messages?meta_message_id=eq.${encodeURIComponent(String(m.key?.id||''))}&select=id&limit=1`).catch(()=>[]);if(m.key?.id&&duplicate?.length)return;
  const contact=await upsertContact(phone,m.pushName||''),recipient=await latestRecipient(phone);
  if(rawJid.endsWith('@lid'))await saveJidMap(`${phone}@s.whatsapp.net`,rawJid);
  await sb('/rest/v1/pz_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({phone,contact_id:contact?.id||null,campaign_id:recipient?.campaign_id||null,recipient_id:recipient?.id||null,meta_message_id:String(m.key?.id||crypto.randomUUID()),direction:fromMe?'OUT':'IN',message_type:type,body:text||null,status:fromMe?'sent':'received',raw_payload:{key:m.key||null,pushName:m.pushName||null,identitySource:identity.source}})}).catch(()=>{});
  if(!recipient)return;
  if(fromMe){
    if(isPurchasePhrase(text)){await recordPurchase(recipient,'AUTO_FRASE',text);return}
    if(['image','pdf','document'].includes(type)&&['PAGAMENTO_APROVADO','AGUARDANDO_BILHETES'].includes(recipient.status)){
      await recordPurchase(recipient,'BILHETES_ENVIADOS',`Mídia enviada pelo operador: ${type}`);const settings=await getSettings();await botSend(recipient.phone,settings.thank_you_message||'🍀 A Reino da Sorte agradece a sua compra. Boa sorte! 🍀').catch(()=>{});return;
    }
    return;
  }
  const campaignRows=await sb(`/rest/v1/pz_campaigns?id=eq.${recipient.campaign_id}&select=*&limit=1`).catch(()=>[]),campaign=campaignRows?.[0]||null;
  const payment=['image','pdf','document'].includes(type)&&['AGUARDANDO_PAGAMENTO','PEDIDO_CONFIRMADO'].includes(recipient.status);
  const baseStatus=payment?'POSSIVEL_PAGAMENTO':(['AGUARDANDO_DADOS','AGUARDANDO_PAGAMENTO'].includes(recipient.status)?recipient.status:'RESPONDEU');
  await sb(`/rest/v1/pz_recipients?id=eq.${recipient.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:baseStatus,responded_at:recipient.responded_at||nowIso(),possible_payment_at:payment?nowIso():recipient.possible_payment_at||null,last_inbound_preview:text||`[${type}]`,last_inbound_type:type,next_action_at:null,updated_at:nowIso()})});
  await handleInboundBot({...recipient,status:baseStatus,responded_at:recipient.responded_at||nowIso()},campaign,contact,text,type).catch(e=>console.log('Bot:',e.message));
}
async function targetJid(phone){const n=normalizeBR(phone);if(!/^55\d{10,11}$/.test(n))throw new Error('Telefone inválido.');const pn=`${n}@s.whatsapp.net`;let jid=pn;try{const fn=sock?.signalRepository?.lidMapping?.getLIDForPN;if(typeof fn==='function'){const lid=await fn.call(sock.signalRepository.lidMapping,pn);if(String(lid||'').endsWith('@lid')){await saveJidMap(pn,lid);jid=lid}}}catch{}if(jid===pn){const ex=await sock.onWhatsApp(pn);jid=ex?.[0]?.jid||pn}return{n,jid}}
async function sendText(phone,text){if(!sock||!connected)throw new Error('WhatsApp não conectado.');const {n,jid}=await targetJid(phone);const r=await sock.sendMessage(jid,{text:String(text||'').trim()});return{to:n,id:r?.key?.id||null}}
async function sendImageText(phone,url,text){if(!sock||!connected)throw new Error('WhatsApp não conectado.');const {n,jid}=await targetJid(phone);const r=await fetch(url);if(!r.ok)throw new Error('Não foi possível carregar a imagem.');const image=Buffer.from(await r.arrayBuffer());const out=await sock.sendMessage(jid,{image,caption:String(text||'').trim()});return{to:n,id:out?.key?.id||null}}
async function ensureBucket(){const r=await fetch(`${SUPABASE_URL}/storage/v1/bucket/${STORAGE_BUCKET}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(r.ok)return;const c=await fetch(`${SUPABASE_URL}/storage/v1/bucket`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({id:STORAGE_BUCKET,name:STORAGE_BUCKET,public:true,file_size_limit:6291456,allowed_mime_types:['image/jpeg','image/png','image/webp']})});if(!c.ok&&!String(await c.text()).toLowerCase().includes('already'))throw new Error('Não foi possível preparar o armazenamento de imagens.')}
async function uploadImage(dataUrl){if(!dataUrl)return null;const m=String(dataUrl).match(/^data:(image\/(?:jpeg|jpg|png|webp));base64,(.+)$/i);if(!m)throw new Error('Imagem inválida.');const mime=m[1].toLowerCase()==='image/jpg'?'image/jpeg':m[1].toLowerCase(),ext=mime.includes('png')?'png':mime.includes('webp')?'webp':'jpg',buf=Buffer.from(m[2],'base64');if(buf.length>6*1024*1024)throw new Error('Imagem maior que 6 MB.');await ensureBucket();const object=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${STORAGE_BUCKET}/${object}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':mime,'x-upsert':'false'},body:buf});if(!r.ok)throw new Error(`Falha ao salvar imagem (${r.status}).`);return`${SUPABASE_URL}/storage/v1/object/public/${STORAGE_BUCKET}/${object}`}
async function campaignSummary(id){const rows=await sb(`/rest/v1/pz_recipients?campaign_id=eq.${id}&select=status`);const c={total:0,pendentes:0,enviados:0,responderam:0,compras:0,falhas:0};for(const r of rows||[]){c.total++;if(['PENDENTE','REENVIO_AGENDADO'].includes(r.status))c.pendentes++;if(['ENVIADA','ENTREGUE','LIDA'].includes(r.status))c.enviados++;if(['RESPONDEU','AGUARDANDO_DADOS','AGUARDANDO_PAGAMENTO','POSSIVEL_PAGAMENTO','PAGAMENTO_APROVADO','AGUARDANDO_BILHETES','EM_NEGOCIACAO'].includes(r.status))c.responderam++;if(r.status==='COMPRA_REALIZADA')c.compras++;if(r.status==='FALHA')c.falhas++}return c}
async function maybeFinalizeCampaign(c){const rows=await sb(`/rest/v1/pz_recipients?campaign_id=eq.${c.id}&select=status,next_action_at`);const active=(rows||[]).some(r=>['PENDENTE','REENVIO_AGENDADO'].includes(r.status)||(['ENVIADA','ENTREGUE','LIDA'].includes(r.status)&&c.retry_enabled&&r.next_action_at));if(!active&&c.status==='EM_EXECUCAO')await sb(`/rest/v1/pz_campaigns?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'FINALIZADA',finished_at:nowIso(),updated_at:nowIso()})})}
async function runDueCampaigns(){if(runnerBusy)return{busy:true};runnerBusy=true;let sent=0,failed=0;try{if(!await ensureConnected(20000))return{connected:false,sent:0};const camps=await sb('/rest/v1/pz_campaigns?status=in.(AGENDADA,EM_EXECUCAO)&select=*&order=created_at.asc&limit=50');for(const c of camps||[]){if(c.status==='AGENDADA'&&c.schedule_at&&new Date(c.schedule_at)>new Date())continue;if(c.status==='AGENDADA')await sb(`/rest/v1/pz_campaigns?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'EM_EXECUCAO',started_at:nowIso(),updated_at:nowIso()})});const due=await sb(`/rest/v1/pz_recipients?campaign_id=eq.${c.id}&status=in.(PENDENTE,REENVIO_AGENDADO,ENVIADA,ENTREGUE,LIDA)&next_action_at=lte.${encodeURIComponent(nowIso())}&select=*&order=next_action_at.asc&limit=1000`);for(const r of due||[]){const fresh=await sb(`/rest/v1/pz_campaigns?id=eq.${c.id}&select=status&limit=1`);if(fresh?.[0]?.status!=='EM_EXECUCAO')break;if(['ENVIADA','ENTREGUE','LIDA'].includes(r.status)&&!c.retry_enabled)continue;if((r.attempt_count||0)>=(r.max_attempts||1)){await sb(`/rest/v1/pz_recipients?id=eq.${r.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'SEM_RESPOSTA',next_action_at:null,updated_at:nowIso()})});continue}try{const msgs=Array.isArray(c.messages)?c.messages:[],text=String(msgs[Math.min(Number(r.selected_message)||0,Math.max(0,msgs.length-1))]||msgs[0]||'').trim();const out=c.image_url?await sendImageText(r.phone,c.image_url,text):await sendText(r.phone,text);const attempts=(r.attempt_count||0)+1;let status='ENVIADA',next=null;if(c.retry_enabled&&attempts<(r.max_attempts||1))next=new Date(Date.now()+(Number(c.retry_hours)||24)*3600000).toISOString();await sb(`/rest/v1/pz_recipients?id=eq.${r.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,attempt_count:attempts,meta_message_id:out.id,sent_at:nowIso(),next_action_at:next,error_text:null,updated_at:nowIso()})});sent++}catch(e){failed++;const attempts=(r.attempt_count||0)+1;const retry=attempts<(r.max_attempts||1);await sb(`/rest/v1/pz_recipients?id=eq.${r.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:retry?'REENVIO_AGENDADO':'FALHA',attempt_count:attempts,next_action_at:retry?new Date(Date.now()+15*60000).toISOString():null,error_text:e.message,updated_at:nowIso()})}).catch(()=>{})}await sleep(randomMs(c.interval_min,c.interval_max))}await maybeFinalizeCampaign({...c,status:'EM_EXECUCAO'})}return{connected:true,sent,failed}}finally{runnerBusy=false}}

app.get('/health',(req,res)=>res.json({ok:true,service:'projeto-zap',version:'5.6.0',connected,runnerBusy}));
app.get('/api/dashboard',async(req,res)=>{try{const [contacts,camps,returns,purchases]=await Promise.all([sb('/rest/v1/pz_contacts?select=id'),sb('/rest/v1/pz_campaigns?select=*&order=created_at.desc&limit=100'),sb('/rest/v1/pz_recipients?status=in.(RESPONDEU,AGUARDANDO_DADOS,AGUARDANDO_PAGAMENTO,POSSIVEL_PAGAMENTO,PAGAMENTO_APROVADO,AGUARDANDO_BILHETES,EM_NEGOCIACAO)&select=id'),sb('/rest/v1/pz_purchases?select=id')]);const scheduled=(camps||[]).filter(c=>c.status==='AGENDADA').length,active=(camps||[]).filter(c=>c.status==='EM_EXECUCAO').length;res.json({ok:true,stats:{contacts:contacts?.length||0,campaigns:camps?.length||0,scheduled,active,returns:returns?.length||0,purchases:purchases?.length||0},next:(camps||[]).filter(c=>c.status==='AGENDADA').sort((a,b)=>String(a.schedule_at).localeCompare(String(b.schedule_at))).slice(0,5)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/whatsapp/status',(req,res)=>res.json({ok:true,connected,starting,number:connectedNumber||null,name:connectedName||null,qrAvailable:Boolean(qrDataUrl),qrDataUrl:qrDataUrl||null,lastError:lastError||null,lastConnectionAt}));
app.post('/api/whatsapp/connect',async(req,res)=>{try{await startWhatsApp(Boolean(req.body?.force));res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/pairing-code',async(req,res)=>{try{const phone=normalizeBR(req.body?.phone);if(!/^55\d{10,11}$/.test(phone))return res.status(400).json({error:'Telefone inválido.'});if(!sock)await startWhatsApp(false);if(connected)return res.json({ok:true,connected:true});await sleep(700);res.json({ok:true,code:await sock.requestPairingCode(phone)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/send-test',async(req,res)=>{try{res.json({ok:true,...await sendText(req.body?.to,req.body?.text||'Teste Projeto Zap V5.7 ✅')})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/logout',async(req,res)=>{try{if(sock)try{await sock.logout()}catch{}await closeSocket(true);await authClear();res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/contacts',async(req,res)=>{try{const rows=await sb('/rest/v1/pz_contacts?select=*&order=name.asc&limit=5000');res.json({ok:true,contacts:rows||[]})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/contacts',async(req,res)=>{try{const phone=normalizeBR(req.body?.phone);if(!/^55\d{10,11}$/.test(phone))return res.status(400).json({error:'Telefone inválido.'});let c=await findContact(phone);const body={name:String(req.body?.name||'').trim()||`Cliente ${phone.slice(-4)}`,phone,city:String(req.body?.city||'').trim(),group_name:String(req.body?.group_name||'GERAL').trim()||'GERAL',status:String(req.body?.status||'ATIVO'),opt_in:req.body?.opt_in!==false,opt_out:Boolean(req.body?.opt_out),notes:String(req.body?.notes||'').trim(),updated_at:nowIso()};if(c){await sb(`/rest/v1/pz_contacts?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});res.json({ok:true,contact:{...c,...body}})}else{const rows=await sb('/rest/v1/pz_contacts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});res.json({ok:true,contact:rows?.[0]})}}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/contacts/:id',async(req,res)=>{try{const body={...req.body,updated_at:nowIso()};if(body.phone)body.phone=normalizeBR(body.phone);await sb(`/rest/v1/pz_contacts?id=eq.${encodeURIComponent(req.params.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/contacts/:id',async(req,res)=>{try{await sb(`/rest/v1/pz_contacts?id=eq.${encodeURIComponent(req.params.id)}`,{method:'DELETE'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/campaigns',async(req,res)=>{try{const rows=await sb('/rest/v1/pz_campaigns?select=*&order=created_at.desc&limit=300');for(const c of rows||[])c.summary=await campaignSummary(c.id);res.json({ok:true,campaigns:rows||[]})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns',async(req,res)=>{try{const name=String(req.body?.name||'').trim(),messages=(Array.isArray(req.body?.messages)?req.body.messages:[]).map(x=>String(x||'').trim()).filter(Boolean).slice(0,5),phones=[...new Set((Array.isArray(req.body?.phones)?req.body.phones:[]).map(normalizeBR).filter(x=>/^55\d{10,11}$/.test(x)))];if(!name)return res.status(400).json({error:'Informe o nome da campanha.'});if(!messages.length)return res.status(400).json({error:'Informe ao menos uma mensagem.'});if(!phones.length)return res.status(400).json({error:'Selecione ao menos um contato.'});const image_url=await uploadImage(req.body?.imageDataUrl),schedule_at=req.body?.scheduleAt?new Date(req.body.scheduleAt).toISOString():null,retry_enabled=Boolean(req.body?.retryEnabled),max_attempts=retry_enabled?Math.max(1,Math.min(5,Number(req.body?.maxAttempts)||2)):1,status=schedule_at&&new Date(schedule_at)>new Date()?'AGENDADA':'PRONTA',unit_price=Math.max(0,Number(req.body?.unitPrice)||0),auto_bot_enabled=req.body?.autoBotEnabled!==false;const rows=await sb('/rest/v1/pz_campaigns',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name,messages,image_url,image_name:req.body?.imageName||null,interval_min:Math.max(3,Number(req.body?.intervalMin)||6),interval_max:Math.max(3,Number(req.body?.intervalMax)||12),schedule_at,retry_enabled,retry_hours:Math.max(1,Number(req.body?.retryHours)||24),max_attempts,status,unit_price,auto_bot_enabled})});const camp=rows?.[0],contacts=await sb('/rest/v1/pz_contacts?select=*&limit=5000'),selected=(contacts||[]).filter(c=>phones.includes(normalizeBR(c.phone))&&c.opt_in!==false&&!c.opt_out);if(!selected.length)throw new Error('Nenhum contato selecionado está autorizado.');const firstAction=status==='AGENDADA'?schedule_at:null,recs=selected.map((c,i)=>({campaign_id:camp.id,contact_id:c.id,phone:normalizeBR(c.phone),name:c.name,status:'PENDENTE',selected_message:i%messages.length,attempt_count:0,max_attempts,next_action_at:firstAction}));await sb('/rest/v1/pz_recipients',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(recs)});res.json({ok:true,campaign:camp,recipients:recs.length})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns/:id/start',async(req,res)=>{try{const id=encodeURIComponent(req.params.id),now=nowIso();await sb(`/rest/v1/pz_campaigns?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'EM_EXECUCAO',started_at:now,updated_at:now})});await sb(`/rest/v1/pz_recipients?campaign_id=eq.${id}&status=eq.PENDENTE`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({next_action_at:now,updated_at:now})});runDueCampaigns().catch(()=>{});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns/:id/pause',async(req,res)=>{try{await sb(`/rest/v1/pz_campaigns?id=eq.${encodeURIComponent(req.params.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'PAUSADA',updated_at:nowIso()})});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns/:id/resume',async(req,res)=>{try{await sb(`/rest/v1/pz_campaigns?id=eq.${encodeURIComponent(req.params.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'EM_EXECUCAO',updated_at:nowIso()})});runDueCampaigns().catch(()=>{});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/campaigns/:id',async(req,res)=>{try{await sb(`/rest/v1/pz_campaigns?id=eq.${encodeURIComponent(req.params.id)}`,{method:'DELETE'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/execution',async(req,res)=>{try{const camps=await sb('/rest/v1/pz_campaigns?select=*&order=created_at.desc&limit=200');for(const c of camps||[])c.summary=await campaignSummary(c.id);res.json({ok:true,campaigns:camps||[]})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/campaigns/:id/recipients',async(req,res)=>{try{const rows=await sb(`/rest/v1/pz_recipients?campaign_id=eq.${encodeURIComponent(req.params.id)}&select=*&order=created_at.asc&limit=5000`);res.json({ok:true,items:rows||[]})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/returns',async(req,res)=>{try{const rows=await sb('/rest/v1/pz_recipients?status=in.(RESPONDEU,AGUARDANDO_DADOS,AGUARDANDO_PAGAMENTO,POSSIVEL_PAGAMENTO,PAGAMENTO_APROVADO,AGUARDANDO_BILHETES,EM_NEGOCIACAO)&select=*,pz_campaigns(name,unit_price)&order=responded_at.desc.nullslast&limit=1000');const ids=(rows||[]).map(r=>r.id);let orders=[];if(ids.length)orders=await sb(`/rest/v1/pz_orders?recipient_id=in.(${ids.join(',')})&select=*&order=created_at.desc`).catch(()=>[]);for(const r of rows||[])r.order=(orders||[]).find(o=>o.recipient_id===r.id)||null;res.json({ok:true,items:rows||[]})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/recipients/:id/status',async(req,res)=>{try{const id=encodeURIComponent(req.params.id),rows=await sb(`/rest/v1/pz_recipients?id=eq.${id}&select=*&limit=1`),r=rows?.[0];if(!r)return res.status(404).json({error:'Registro não encontrado.'});const status=String(req.body?.status||'');if(status==='COMPRA_REALIZADA')await recordPurchase(r,'MANUAL',String(req.body?.notes||''));else await sb(`/rest/v1/pz_recipients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,next_action_at:['RESPONDEU','POSSIVEL_PAGAMENTO','EM_NEGOCIACAO','NAO_INTERESSADO'].includes(status)?null:r.next_action_at,updated_at:nowIso()})});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/settings',async(req,res)=>{try{res.json({ok:true,settings:await getSettings()})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/settings',async(req,res)=>{try{const body={id:'main',bot_enabled:req.body?.bot_enabled!==false,pix_key:String(req.body?.pix_key||'').trim(),pix_name:String(req.body?.pix_name||'REINO DA SORTE').trim(),trigger_keywords:(Array.isArray(req.body?.trigger_keywords)?req.body.trigger_keywords:String(req.body?.trigger_keywords||'').split(',')).map(x=>String(x).trim()).filter(Boolean).slice(0,30),order_prompt:String(req.body?.order_prompt||'').trim()||'Para fazer seu pedido, responda preenchendo:\nNome:\nQuantidade:\nContato:',thank_you_message:String(req.body?.thank_you_message||'').trim()||'🍀 A Reino da Sorte agradece a sua compra. Boa sorte! 🍀',updated_at:nowIso()};await sb('/rest/v1/pz_settings?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/recipients/:id/confirm-payment',async(req,res)=>{try{const id=encodeURIComponent(req.params.id),rows=await sb(`/rest/v1/pz_recipients?id=eq.${id}&select=*&limit=1`),r=rows?.[0];if(!r)return res.status(404).json({error:'Registro não encontrado.'});await sb(`/rest/v1/pz_recipients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'AGUARDANDO_BILHETES',updated_at:nowIso()})});const o=await getOrder(r.id);if(o)await sb(`/rest/v1/pz_orders?id=eq.${o.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'PAGAMENTO_APROVADO',operator_confirmed_at:nowIso(),updated_at:nowIso()})});await botSend(r.phone,'✅ Pagamento confirmado. Estamos gerando seus bilhetes.').catch(()=>{});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/recipients/:id/finalize',async(req,res)=>{try{const id=encodeURIComponent(req.params.id),rows=await sb(`/rest/v1/pz_recipients?id=eq.${id}&select=*&limit=1`),r=rows?.[0];if(!r)return res.status(404).json({error:'Registro não encontrado.'});await recordPurchase(r,'OPERADOR','Finalização manual após envio dos bilhetes');const settings=await getSettings();await botSend(r.phone,settings.thank_you_message||'🍀 A Reino da Sorte agradece a sua compra. Boa sorte! 🍀').catch(()=>{});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/purchases',async(req,res)=>{try{const rows=await sb('/rest/v1/pz_purchases?select=*,pz_campaigns(name)&order=created_at.desc&limit=1000');res.json({ok:true,items:rows||[]})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/cron/process',async(req,res)=>{if(CRON_SECRET&&req.headers['x-cron-secret']!==CRON_SECRET)return res.status(401).json({error:'Não autorizado.'});res.status(202).json({ok:true,accepted:true});setTimeout(()=>runDueCampaigns().catch(e=>console.log('Cron:',e.message)),50)});
app.post('/api/run-now',async(req,res)=>{try{res.json({ok:true,...await runDueCampaigns()})}catch(e){res.status(500).json({error:e.message})}});
app.get('/',(req,res)=>res.sendFile(__dirname+'/index.html'));
app.listen(PORT,async()=>{console.log(`Projeto Zap V5.7 online na porta ${PORT}`);try{await startWhatsApp(false)}catch(e){console.log('WhatsApp aguardando:',e.message)}setInterval(()=>runDueCampaigns().catch(()=>{}),30000)});
