const express=require('express');
const path=require('path');
const crypto=require('crypto');
const pino=require('pino');
const QRCode=require('qrcode');
const {default:makeWASocket,DisconnectReason,fetchLatestBaileysVersion,initAuthCreds,BufferJSON,proto,jidNormalizedUser}=require('@whiskeysockets/baileys');

const app=express();
app.use(express.json({limit:'30mb'}));
app.use(express.static(__dirname,{extensions:['html']}));
const PORT=process.env.PORT||3000;
const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/+$/,'');
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
function needDb(){if(!SUPABASE_URL||!KEY)throw new Error('Configure SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY no Render.');}
async function sb(p,opt={}){needDb();const r=await fetch(SUPABASE_URL+p,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||`Supabase ${r.status}`);return d}
const digits=v=>String(v||'').replace(/\D/g,'');
function phone(v){let n=digits(v);if(n.startsWith('00'))n=n.slice(2);if(!n.startsWith('55')&&(n.length===10||n.length===11))n='55'+n;return n}
const validPhone=n=>/^55\d{10,11}$/.test(phone(n));
const now=()=>new Date().toISOString();
const q=s=>encodeURIComponent(String(s??''));
function orderCode(){return 'RDS-'+Date.now().toString(36).toUpperCase().slice(-6)+'-'+crypto.randomInt(100,999)}
async function patch(table,id,data){await sb(`/rest/v1/${table}?id=eq.${q(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...data,updated_at:now()})})}
async function settings(){const x=await sb('/rest/v1/rds_settings?id=eq.main&select=*&limit=1');return x?.[0]||{}}
async function event(type,data={}){try{await sb('/rest/v1/rds_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({event_type:type,phone:data.phone||null,campaign_id:data.campaign_id||null,order_id:data.order_id||null,payload:data.payload||{}})})}catch{}}
async function findContact(n){const rows=await sb(`/rest/v1/rds_contacts?phone=eq.${q(phone(n))}&select=*&limit=1`);return rows?.[0]||null}
async function ensureContact(n){let c=await findContact(n);if(c)return c;const s=await settings();if(s.auto_create_contacts===false)return null;const p=phone(n);const rows=await sb('/rest/v1/rds_contacts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:`WhatsApp ${p.slice(-4)}`,phone:p,group_name:'ENTRADA WHATSAPP',status:'ATIVO',notes:'Criado automaticamente por mensagem recebida.',source:'WHATSAPP',last_interaction_at:now()})});return rows?.[0]||null}
async function activeRecipient(n){const rows=await sb(`/rest/v1/rds_campaign_recipients?phone=eq.${q(phone(n))}&recipient_status=in.(ATIVO,ENVIADO,ENTREGUE,LIDO)&select=*&order=created_at.desc&limit=1`);return rows?.[0]||null}
async function activeOrder(n){const rows=await sb(`/rest/v1/rds_orders?phone=eq.${q(phone(n))}&status=in.(COLETANDO_DADOS,AGUARDANDO_PAGAMENTO,COMPROVANTE_RECEBIDO,PAGAMENTO_CONFIRMADO)&select=*&order=created_at.desc&limit=1`);return rows?.[0]||null}
async function saveMessage({contact,campaign_id,recipient_id,order_id,phone:ph,id,direction,type,body,mime,file}){try{await sb('/rest/v1/rds_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({contact_id:contact?.id||null,campaign_id:campaign_id||null,recipient_id:recipient_id||null,order_id:order_id||null,phone:phone(ph),wa_message_id:id||null,direction,message_type:type||'text',body:body||null,mime_type:mime||null,file_name:file||null})})}catch{}}
async function upsertConversation(ph,data={}){const p=phone(ph);const existing=await sb(`/rest/v1/rds_conversations?phone=eq.${q(p)}&select=*&limit=1`);const base=existing?.[0]||null;if(base){await patch('rds_conversations',base.id,data);return {...base,...data}}const rows=await sb('/rest/v1/rds_conversations',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({phone:p,...data})});return rows?.[0]||null}

let sock=null,connected=false,starting=false,qrDataUrl='',connectedNumber='',lastError='';
const messageStore=new Map();
function keepMessage(m){const id=m?.key?.id;if(!id)return;messageStore.set(id,m);if(messageStore.size>500){const first=messageStore.keys().next().value;messageStore.delete(first)}}
async function authRead(id){const r=await sb(`/rest/v1/zap_auth?id=eq.${q(id)}&select=value&limit=1`);return r?.[0]?JSON.parse(JSON.stringify(r[0].value),BufferJSON.reviver):null}
async function authWrite(id,value){const safe=JSON.parse(JSON.stringify(value,BufferJSON.replacer));await sb('/rest/v1/zap_auth?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id,value:safe,updated_at:now()})})}
async function authDelete(id){await sb(`/rest/v1/zap_auth?id=eq.${q(id)}`,{method:'DELETE'})}
async function authState(){const creds=(await authRead('creds'))||initAuthCreds();return{state:{creds,keys:{get:async(type,ids)=>{const out={};for(const id of ids){let v=await authRead(`${type}-${id}`);if(type==='app-state-sync-key'&&v)v=proto.Message.AppStateSyncKeyData.fromObject(v);out[id]=v}return out},set:async(data)=>{for(const cat of Object.keys(data))for(const id of Object.keys(data[cat]))data[cat][id]?await authWrite(`${cat}-${id}`,data[cat][id]):await authDelete(`${cat}-${id}`)}}},saveCreds:()=>authWrite('creds',creds)}}
async function closeSock(){try{sock?.ws?.close?.()}catch{}sock=null;connected=false;connectedNumber=''}
async function updateDeliveryAck(id,status){if(!id)return;const rows=await sb(`/rest/v1/rds_deliveries?wa_message_id=eq.${q(id)}&select=id,recipient_id,status&limit=1`);const d=rows?.[0];if(!d)return;let next=null,extra={};const n=Number(status);if(n>=4){next='LIDA';extra.read_at=now()}else if(n>=3){next='ENTREGUE';extra.delivered_at=now()}else if(n===0){next='FALHA'}if(!next)return;await patch('rds_deliveries',d.id,{status:next,...extra});if(next==='ENTREGUE'||next==='LIDA')await patch('rds_campaign_recipients',d.recipient_id,{recipient_status:next})}
async function startWA(force=false){if(starting)return;if(sock&&!force)return;starting=true;if(force)await closeSock();try{const {state,saveCreds}=await authState();const {version}=await fetchLatestBaileysVersion();sock=makeWASocket({version,auth:state,logger:pino({level:'silent'}),printQRInTerminal:false,browser:['CANAL DE VENDAS RDS','Chrome','6.1.0'],markOnlineOnConnect:false,syncFullHistory:false,shouldSyncHistoryMessage:()=>false,generateHighQualityLinkPreview:false,getMessage:async key=>messageStore.get(key.id)?.message||undefined});sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',async u=>{if(u.qr){qrDataUrl=await QRCode.toDataURL(u.qr,{width:420,margin:2});lastError=''}if(u.connection==='open'){connected=true;qrDataUrl='';connectedNumber=digits(sock.user?.id?.split(':')?.[0]||sock.user?.id||'');lastError=''}if(u.connection==='close'){connected=false;const code=u.lastDisconnect?.error?.output?.statusCode||u.lastDisconnect?.error?.statusCode||0;const out=code===DisconnectReason.loggedOut;lastError=String(u.lastDisconnect?.error?.message||'Conexão encerrada');await closeSock();if(!out)setTimeout(()=>startWA(false).catch(()=>{}),3000)}});sock.ev.on('messages.upsert',async({messages,type})=>{if(!['notify','append'].includes(type))return;for(const m of messages||[]){if(!m?.message)continue;keepMessage(m);const remote=String(m.key.remoteJid||'');if(remote.endsWith('@g.us')||remote==='status@broadcast'||remote.endsWith('@newsletter'))continue;if(m.key?.fromMe){await outboundObserved(m).catch(()=>{});continue}await inbound(remote,m).catch(e=>console.error('inbound',e.message))}});sock.ev.on('messages.update',async updates=>{for(const u of updates||[])await updateDeliveryAck(u.key?.id,u.update?.status).catch(()=>{})})}catch(e){lastError=e.message;await closeSock();throw e}finally{starting=false}}
async function resolveJid(to){if(!sock||!connected)throw new Error('WhatsApp não conectado.');const n=phone(to);if(!validPhone(n))throw new Error('Telefone inválido.');try{const rows=await sock.onWhatsApp(n);const hit=rows?.find(x=>x.exists)||rows?.[0];if(hit?.jid)return jidNormalizedUser(hit.jid)}catch{}return `${n}@s.whatsapp.net`}
async function sendText(to,text){const jid=await resolveJid(to);const r=await sock.sendMessage(jid,{text:String(text||'').trim()});keepMessage(r);await saveMessage({phone:to,id:r?.key?.id,direction:'OUT',type:'text',body:text});await upsertConversation(to,{last_outbound_at:now()}).catch(()=>{});return{messageId:r?.key?.id||null,jid}}
async function sendCampaignMessage(to,text,imageData){const jid=await resolveJid(to);let r;if(imageData){const m=String(imageData).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('Imagem inválida.');r=await sock.sendMessage(jid,{image:Buffer.from(m[2],'base64'),mimetype:m[1],caption:text})}else r=await sock.sendMessage(jid,{text});keepMessage(r);await saveMessage({phone:to,id:r?.key?.id,direction:'OUT',type:imageData?'image':'text',body:text});await upsertConversation(to,{last_outbound_at:now()}).catch(()=>{});return{messageId:r?.key?.id||null,jid}}
function extractMsg(m){let x=m.message||{};if(x.ephemeralMessage?.message)x=x.ephemeralMessage.message;if(x.viewOnceMessage?.message)x=x.viewOnceMessage.message;if(x.viewOnceMessageV2?.message)x=x.viewOnceMessageV2.message;if(x.conversation)return{type:'text',body:x.conversation};if(x.extendedTextMessage)return{type:'text',body:x.extendedTextMessage.text||''};if(x.imageMessage)return{type:'image',body:x.imageMessage.caption||'',mime:x.imageMessage.mimetype||'image/jpeg',file:'imagem'};if(x.documentMessage)return{type:'document',body:x.documentMessage.caption||'',mime:x.documentMessage.mimetype||'',file:x.documentMessage.fileName||'documento'};return{type:'other',body:''}}
function remotePhone(remote,m){const r=String(remote||'');if(r.endsWith('@lid')){const p=digits(m?.key?.participant||'');if(p)return phone(p.split(':')[0])}return phone(digits(r.split('@')[0]).split(':')[0])}
function parseOrderForm(t){const s=String(t||'');const name=(s.match(/nome\s*:\s*([^\n]+)/i)||[])[1]?.trim();const qty=Number((s.match(/quantidade\s*:\s*(\d+)/i)||[])[1]||0);const contact=digits((s.match(/contato\s*:\s*([^\n]+)/i)||[])[1]||'');return{name,qty,contact}}
function extractQty(t){const s=String(t||'');const m=s.match(/(?:quero|comprar|compra|bilhete|bilhetes|pedido)?\s*(\d{1,4})\s*(?:bilhete|bilhetes)?/i);return m?Number(m[1]):0}
function wantsBuy(t){return /\b(quero|comprar|compra|bilhete|bilhetes|pedido|reserve|reservar|garantir|me dê|me de)\b/i.test(String(t||''))||/RDS-COMPRAR/i.test(String(t||''))}
async function cancelFuture(recipientId){if(!recipientId)return;await sb(`/rest/v1/rds_deliveries?recipient_id=eq.${q(recipientId)}&status=eq.AGENDADA`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'CANCELADA',updated_at:now()})});await patch('rds_campaign_recipients',recipientId,{recipient_status:'RESPONDEU',responded_at:now()})}
async function startOrder(ph,contact,recipient,campaignId,qty=0){const s=await settings();let campaign=null;if(campaignId){const r=await sb(`/rest/v1/rds_campaigns?id=eq.${q(campaignId)}&select=*&limit=1`);campaign=r?.[0]}if(!campaign&&recipient){const r=await sb(`/rest/v1/rds_campaigns?id=eq.${q(recipient.campaign_id)}&select=*&limit=1`);campaign=r?.[0]}const rows=await sb('/rest/v1/rds_orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({code:orderCode(),campaign_id:campaign?.id||null,recipient_id:recipient?.id||null,contact_id:contact?.id||null,phone:phone(ph),unit_price:Number(campaign?.unit_price||s.ticket_price||3),quantity:qty||null,status:'COLETANDO_DADOS'})});const o=rows[0];await cancelFuture(recipient?.id);await upsertConversation(ph,{contact_id:contact?.id||null,stage:'COLETANDO_DADOS',current_order_id:o.id,current_campaign_id:o.campaign_id,unread_count:0});await sendText(ph,`${s.order_prompt}\n\nPedido: ${o.code}${qty?`\nQuantidade solicitada: ${qty}`:''}`);await event('PEDIDO_INICIADO',{phone:ph,campaign_id:o.campaign_id,order_id:o.id});return o}
async function inbound(remote,m){const ph=remotePhone(remote,m);if(!validPhone(ph))return;const msg=extractMsg(m),contact=await ensureContact(ph),recipient=await activeRecipient(ph);let order=await activeOrder(ph);if(contact)await patch('rds_contacts',contact.id,{last_interaction_at:now()});await saveMessage({contact,campaign_id:recipient?.campaign_id,recipient_id:recipient?.id,order_id:order?.id,phone:ph,id:m.key?.id,direction:'IN',type:msg.type,body:msg.body,mime:msg.mime,file:msg.file});const conv=await upsertConversation(ph,{contact_id:contact?.id||null,stage:order?.status||'RESPONDEU',unread_count:1,last_inbound_text:msg.body||`[${msg.type}]`,last_inbound_at:now(),current_order_id:order?.id||null,current_campaign_id:recipient?.campaign_id||order?.campaign_id||null});if(recipient)await cancelFuture(recipient.id);const s=await settings();if(!s.bot_enabled)return;
  if((msg.type==='image'||msg.type==='document')&&order&&['AGUARDANDO_PAGAMENTO','COLETANDO_DADOS'].includes(order.status)){await patch('rds_orders',order.id,{status:'COMPROVANTE_RECEBIDO',proof_type:msg.type,proof_received_at:now()});await upsertConversation(ph,{stage:'COMPROVANTE_RECEBIDO',current_order_id:order.id});await sendText(ph,s.proof_received_message);await event('COMPROVANTE_RECEBIDO',{phone:ph,order_id:order.id,campaign_id:order.campaign_id});return}
  if(order?.status==='COLETANDO_DADOS'){const f=parseOrderForm(msg.body);const qty=f.qty||order.quantity||extractQty(msg.body);if(f.name&&qty>0){const total=Number(order.unit_price||s.ticket_price||3)*qty;await patch('rds_orders',order.id,{customer_name:f.name,quantity:qty,contact_phone:f.contact||phone(ph),total_amount:total,status:'AGUARDANDO_PAGAMENTO'});await upsertConversation(ph,{stage:'AGUARDANDO_PAGAMENTO',current_order_id:order.id});await sendText(ph,`✅ Pedido recebido\nPedido: ${order.code}\nQuantidade: ${qty} bilhete(s)\nValor: ${total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}\n\n💳 PIX: ${s.pix_key}\nFavorecido: ${s.pix_name}\n\nApós pagar, envie o comprovante aqui.`);return}await sendText(ph,`Para continuar o pedido, preencha assim:\n\nNome:\nQuantidade:${qty?` ${qty}`:''}\nContato:`);return}
  if(wantsBuy(msg.body)){let campaignId=null;const token=String(msg.body).match(/RDS-COMPRAR:([0-9a-f-]{36})/i);if(token)campaignId=token[1];await startOrder(ph,contact,recipient,campaignId,extractQty(msg.body));return}
  const cooldown=Math.max(0,Number(s.bot_cooldown_seconds||12))*1000;const last=conv?.bot_last_reply_at?new Date(conv.bot_last_reply_at).getTime():0;if(Date.now()-last<cooldown)return;const sales=connectedNumber?`https://wa.me/${connectedNumber}?text=${encodeURIComponent('QUERO COMPRAR')}`:'';const office=s.office_whatsapp?`https://wa.me/${phone(s.office_whatsapp)}`:'';await sendText(ph,`${s.unknown_reply}${sales?`\n\n🛒 Comprar agora: ${sales}`:''}${office?`\n🏢 Falar com o escritório: ${office}`:''}`);await upsertConversation(ph,{stage:'ORIENTADO',bot_last_reply_at:now()})}
async function outboundObserved(m){const ph=remotePhone(m.key?.remoteJid,m);if(!validPhone(ph))return;keepMessage(m);const msg=extractMsg(m);await saveMessage({phone:ph,id:m.key?.id,direction:'OUT',type:msg.type,body:msg.body,mime:msg.mime,file:msg.file});await upsertConversation(ph,{last_outbound_at:now()}).catch(()=>{})}

async function campaignContacts(campaign){if(campaign.target_mode==='custom'){const ids=Array.isArray(campaign.selected_contact_ids)?campaign.selected_contact_ids:[];if(!ids.length)return[];return await sb(`/rest/v1/rds_contacts?id=in.(${ids.map(q).join(',')})&status=eq.ATIVO&select=*`)}if(campaign.target_mode==='group')return await sb(`/rest/v1/rds_contacts?group_name=eq.${q(campaign.target_group)}&status=eq.ATIVO&select=*`);return await sb('/rest/v1/rds_contacts?status=eq.ATIVO&select=*')}
async function createDeliveries(campaign){const contacts=await campaignContacts(campaign);if(!contacts.length)throw new Error('Nenhum contato elegível selecionado.');const steps=await sb(`/rest/v1/rds_campaign_steps?campaign_id=eq.${q(campaign.id)}&select=*&order=step_index.asc`);for(const c of contacts){const recs=await sb('/rest/v1/rds_campaign_recipients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({campaign_id:campaign.id,contact_id:c.id,phone:c.phone,recipient_status:'ATIVO'})});const rec=recs[0];let when=new Date(campaign.start_at);for(const step of steps){if(step.step_index>1)when=new Date(when.getTime()+Number(step.delay_minutes||0)*60000);await sb('/rest/v1/rds_deliveries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({campaign_id:campaign.id,recipient_id:rec.id,contact_id:c.id,phone:c.phone,step_id:step.id,step_index:step.step_index,scheduled_at:when.toISOString(),status:'AGENDADA'})})}}}
async function rebuildCampaign(campaignId){await sb(`/rest/v1/rds_deliveries?campaign_id=eq.${q(campaignId)}`,{method:'DELETE'});await sb(`/rest/v1/rds_campaign_recipients?campaign_id=eq.${q(campaignId)}`,{method:'DELETE'});const c=(await sb(`/rest/v1/rds_campaigns?id=eq.${q(campaignId)}&select=*&limit=1`))[0];await createDeliveries(c)}
async function processDue(){if(!connected)return 0;const due=await sb(`/rest/v1/rds_deliveries?status=eq.AGENDADA&scheduled_at=lte.${q(now())}&select=*&order=scheduled_at.asc&limit=50`);let count=0;for(const d of due||[]){try{const camp=(await sb(`/rest/v1/rds_campaigns?id=eq.${q(d.campaign_id)}&select=status&limit=1`))?.[0];if(!camp||camp.status==='PAUSADA'){continue}const rec=(await sb(`/rest/v1/rds_campaign_recipients?id=eq.${q(d.recipient_id)}&select=*&limit=1`))?.[0];if(!rec||['RESPONDEU','COMPRA'].includes(rec.recipient_status)){await patch('rds_deliveries',d.id,{status:'CANCELADA'});continue}if(await activeOrder(d.phone)){await patch('rds_deliveries',d.id,{status:'CANCELADA'});continue}const step=(await sb(`/rest/v1/rds_campaign_steps?id=eq.${q(d.step_id)}&select=*&limit=1`))?.[0];let text=step.message||'';if(step.cta_enabled&&connectedNumber){const link=`https://wa.me/${connectedNumber}?text=${encodeURIComponent(`QUERO COMPRAR RDS-COMPRAR:${d.campaign_id}`)}`;text+=`\n\n🛒 *PEDIR AGORA:* ${link}`}const r=await sendCampaignMessage(d.phone,text,step.image_data_url);await patch('rds_deliveries',d.id,{status:'ENVIADA_SERVIDOR',sent_at:now(),wa_message_id:r.messageId,target_jid:r.jid,error_text:null});await patch('rds_campaign_recipients',d.recipient_id,{recipient_status:'ENVIADO'});count++;await new Promise(r=>setTimeout(r,2200))}catch(e){await patch('rds_deliveries',d.id,{status:'FALHA',error_text:e.message})}}
  const cids=[...new Set((due||[]).map(x=>x.campaign_id))];for(const id of cids){const pending=await sb(`/rest/v1/rds_deliveries?campaign_id=eq.${q(id)}&status=eq.AGENDADA&select=id&limit=1`);if(!pending.length)await patch('rds_campaigns',id,{status:'FINALIZADA'})}return count}
setInterval(()=>processDue().catch(()=>{}),30000);

app.get('/api/health',async(req,res)=>{try{const s=await settings();res.json({ok:true,db:true,whatsapp:{connected,number:connectedNumber,error:lastError},bot:{enabled:s.bot_enabled,updated_at:s.updated_at,last_test_at:s.last_bot_test_at}})}catch(e){res.status(500).json({ok:false,db:false,error:e.message,whatsapp:{connected,number:connectedNumber,error:lastError}})}});
app.get('/api/whatsapp/status',(req,res)=>res.json({connected,number:connectedNumber,error:lastError,hasQr:!!qrDataUrl}));
app.get('/api/whatsapp/qr',(req,res)=>res.json({qrDataUrl}));
app.post('/api/whatsapp/connect',async(req,res)=>{try{await startWA(true);res.json({ok:true,message:'Conexão iniciada.'})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/pairing-code',async(req,res)=>{try{const n=phone(req.body.phone);if(!validPhone(n))throw new Error('Telefone inválido.');if(!sock)await startWA(false);if(connected)return res.json({ok:true,message:'WhatsApp já conectado.'});const code=await sock.requestPairingCode(n);res.json({ok:true,code})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/logout',async(req,res)=>{try{await sock?.logout?.();await closeSock();res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/send-test',async(req,res)=>{try{const r=await sendText(req.body.to,req.body.text||'Teste CANAL DE VENDAS RDS V6.1 ✅');res.json({ok:true,...r})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/whatsapp/check',async(req,res)=>{try{const n=phone(req.body.phone);if(!connected)throw new Error('WhatsApp não conectado.');const rows=await sock.onWhatsApp(n);const hit=rows?.find(x=>x.exists)||rows?.[0];res.json({ok:true,exists:!!hit?.exists,jid:hit?.jid||null})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/settings',async(req,res)=>{try{res.json({item:await settings()})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/settings',async(req,res)=>{try{await sb('/rest/v1/rds_settings?id=eq.main',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...req.body,updated_at:now()})});res.json({ok:true,saved_at:now()})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/settings/test-bot',async(req,res)=>{try{const s=await settings();const to=req.body.to;await sendText(to,`${s.unknown_reply}\n\n✅ Teste do bot V6.1`);await sb('/rest/v1/rds_settings?id=eq.main',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_bot_test_at:now(),updated_at:now()})});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/contacts',async(req,res)=>{try{res.json({items:await sb('/rest/v1/rds_contacts?select=*&order=name.asc')})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/contacts',async(req,res)=>{try{const p=phone(req.body.phone);if(!validPhone(p))throw new Error('WhatsApp inválido.');const data={name:String(req.body.name||'').trim()||`Contato ${p.slice(-4)}`,phone:p,group_name:req.body.group_name||'NOVOS',status:req.body.status||'ATIVO',notes:req.body.notes||'',city:req.body.city||'',tags:req.body.tags||'',updated_at:now()};if(req.body.id)await patch('rds_contacts',req.body.id,data);else await sb('/rest/v1/rds_contacts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({...data,source:'MANUAL'})});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/contacts/:id',async(req,res)=>{try{await sb(`/rest/v1/rds_contacts?id=eq.${q(req.params.id)}`,{method:'DELETE'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/contacts/:id/validate',async(req,res)=>{try{const c=(await sb(`/rest/v1/rds_contacts?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];if(!c)throw new Error('Contato não encontrado.');if(!connected)throw new Error('WhatsApp não conectado.');const rows=await sock.onWhatsApp(c.phone);const hit=rows?.find(x=>x.exists)||rows?.[0];await patch('rds_contacts',c.id,{wa_valid:!!hit?.exists,wa_checked_at:now()});res.json({ok:true,exists:!!hit?.exists})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/contacts/preview-import',async(req,res)=>{try{const existing=await sb('/rest/v1/rds_contacts?select=phone');const set=new Set(existing.map(x=>phone(x.phone)));const seen=new Set();const items=(req.body.items||[]).map(x=>{const p=phone(x.phone),invalid=!validPhone(p),duplicate=set.has(p)||seen.has(p);seen.add(p);return{name:String(x.name||'').trim(),phone:p,group_name:x.group_name||'IMPORTADOS',city:x.city||'',tags:x.tags||'',invalid,duplicate}});res.json({items})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/contacts/import',async(req,res)=>{let saved=0,skipped=0;try{for(const x of req.body.items||[]){const p=phone(x.phone);if(!validPhone(p)){skipped++;continue}try{await sb('/rest/v1/rds_contacts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:x.name||`Contato ${p.slice(-4)}`,phone:p,group_name:x.group_name||'IMPORTADOS',status:'ATIVO',notes:'',city:x.city||'',tags:x.tags||'',source:'IMPORTACAO'})});saved++}catch{skipped++}}res.json({ok:true,saved,skipped})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/campaigns',async(req,res)=>{try{const cs=await sb('/rest/v1/rds_campaigns?archived=eq.false&select=*&order=created_at.desc');for(const c of cs){c.steps=(await sb(`/rest/v1/rds_campaign_steps?campaign_id=eq.${q(c.id)}&select=id`)).length;const ds=await sb(`/rest/v1/rds_deliveries?campaign_id=eq.${q(c.id)}&select=status`);c.total=ds.length;c.queued=ds.filter(x=>x.status==='AGENDADA').length;c.sent=ds.filter(x=>['ENVIADA_SERVIDOR','ENTREGUE','LIDA'].includes(x.status)).length;c.delivered=ds.filter(x=>['ENTREGUE','LIDA'].includes(x.status)).length;c.read=ds.filter(x=>x.status==='LIDA').length;c.failed=ds.filter(x=>x.status==='FALHA').length;c.cancelled=ds.filter(x=>x.status==='CANCELADA').length}res.json({items:cs})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/campaigns/:id',async(req,res)=>{try{const item=(await sb(`/rest/v1/rds_campaigns?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];const steps=await sb(`/rest/v1/rds_campaign_steps?campaign_id=eq.${q(req.params.id)}&select=*&order=step_index.asc`);const deliveries=await sb(`/rest/v1/rds_deliveries?campaign_id=eq.${q(req.params.id)}&select=*&order=scheduled_at.asc`);res.json({item,steps,deliveries})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns',async(req,res)=>{try{if(!req.body.name||!req.body.start_at)throw new Error('Nome e horário são obrigatórios.');if(!Array.isArray(req.body.steps)||!req.body.steps.length)throw new Error('Adicione pelo menos uma mensagem.');const rows=await sb('/rest/v1/rds_campaigns',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:req.body.name,unit_price:Number(req.body.unit_price||3),start_at:new Date(req.body.start_at).toISOString(),target_mode:req.body.target_mode||'all',target_group:req.body.target_group||null,selected_contact_ids:req.body.selected_contact_ids||[],status:'RASCUNHO'})});const c=rows[0];for(let i=0;i<req.body.steps.length;i++){const s=req.body.steps[i];await sb('/rest/v1/rds_campaign_steps',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({campaign_id:c.id,step_index:i+1,delay_minutes:i===0?0:Number(s.delay_minutes||0),message:s.message||'',image_data_url:s.image_data_url||null,image_name:s.image_name||null,cta_enabled:s.cta_enabled!==false})})}await createDeliveries(c);await patch('rds_campaigns',c.id,{status:'AGENDADA'});res.json({ok:true,id:c.id})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/campaigns/:id',async(req,res)=>{try{const sent=await sb(`/rest/v1/rds_deliveries?campaign_id=eq.${q(req.params.id)}&status=in.(ENVIADA_SERVIDOR,ENTREGUE,LIDA)&select=id&limit=1`);if(sent.length)throw new Error('Campanha já iniciou. Duplique para criar uma nova versão.');await patch('rds_campaigns',req.params.id,{name:req.body.name,unit_price:Number(req.body.unit_price||3),start_at:new Date(req.body.start_at).toISOString(),target_mode:req.body.target_mode||'all',target_group:req.body.target_group||null,selected_contact_ids:req.body.selected_contact_ids||[],status:'AGENDADA'});await sb(`/rest/v1/rds_campaign_steps?campaign_id=eq.${q(req.params.id)}`,{method:'DELETE'});for(let i=0;i<req.body.steps.length;i++){const s=req.body.steps[i];await sb('/rest/v1/rds_campaign_steps',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({campaign_id:req.params.id,step_index:i+1,delay_minutes:i===0?0:Number(s.delay_minutes||0),message:s.message||'',image_data_url:s.image_data_url||null,image_name:s.image_name||null,cta_enabled:s.cta_enabled!==false})})}await rebuildCampaign(req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/campaigns/:id/pause',async(req,res)=>{try{await patch('rds_campaigns',req.params.id,{status:'PAUSADA',paused_at:now()});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns/:id/resume',async(req,res)=>{try{await patch('rds_campaigns',req.params.id,{status:'AGENDADA',paused_at:null});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/campaigns/:id/duplicate',async(req,res)=>{try{const src=(await sb(`/rest/v1/rds_campaigns?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];const steps=await sb(`/rest/v1/rds_campaign_steps?campaign_id=eq.${q(req.params.id)}&select=*&order=step_index.asc`);const rows=await sb('/rest/v1/rds_campaigns',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:`${src.name} - CÓPIA`,unit_price:src.unit_price,start_at:new Date(Date.now()+3600000).toISOString(),target_mode:src.target_mode,target_group:src.target_group,selected_contact_ids:src.selected_contact_ids||[],status:'RASCUNHO'})});const c=rows[0];for(const s of steps)await sb('/rest/v1/rds_campaign_steps',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({campaign_id:c.id,step_index:s.step_index,delay_minutes:s.delay_minutes,message:s.message,image_data_url:s.image_data_url,image_name:s.image_name,cta_enabled:s.cta_enabled})});res.json({ok:true,id:c.id})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/campaigns/:id',async(req,res)=>{try{await sb(`/rest/v1/rds_campaigns?id=eq.${q(req.params.id)}`,{method:'DELETE'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/process',async(req,res)=>{try{res.json({ok:true,processed:await processDue()})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/deliveries',async(req,res)=>{try{const items=await sb('/rest/v1/rds_deliveries?select=*&order=scheduled_at.desc&limit=300');for(const d of items){const c=d.contact_id?(await sb(`/rest/v1/rds_contacts?id=eq.${q(d.contact_id)}&select=name&limit=1`))[0]:null;const ca=(await sb(`/rest/v1/rds_campaigns?id=eq.${q(d.campaign_id)}&select=name&limit=1`))[0];d.contact_name=c?.name||d.phone;d.campaign_name=ca?.name||''}res.json({items})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/orders',async(req,res)=>{try{res.json({items:await sb('/rest/v1/rds_orders?select=*&order=updated_at.desc')})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/orders/:id/confirm-payment',async(req,res)=>{try{const o=(await sb(`/rest/v1/rds_orders?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];await patch('rds_orders',req.params.id,{status:'PAGAMENTO_CONFIRMADO',payment_confirmed_at:now()});await upsertConversation(o.phone,{stage:'PAGAMENTO_CONFIRMADO',current_order_id:o.id});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/orders/:id/reject-proof',async(req,res)=>{try{const o=(await sb(`/rest/v1/rds_orders?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];await patch('rds_orders',o.id,{status:'AGUARDANDO_PAGAMENTO',proof_type:null,proof_received_at:null});await upsertConversation(o.phone,{stage:'AGUARDANDO_PAGAMENTO'});if(connected)await sendText(o.phone,`❌ O comprovante do pedido ${o.code} não foi confirmado. Verifique e envie novamente.`);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/orders/:id/tickets-sent',async(req,res)=>{try{const o=(await sb(`/rest/v1/rds_orders?id=eq.${q(req.params.id)}&select=*&limit=1`))[0],s=await settings();await patch('rds_orders',o.id,{status:'COMPRA_CONCLUIDA',tickets_sent_at:now(),completed_at:now()});await upsertConversation(o.phone,{stage:'COMPRA_CONCLUIDA',current_order_id:o.id,unread_count:0});if(o.contact_id){const c=(await sb(`/rest/v1/rds_contacts?id=eq.${q(o.contact_id)}&select=*&limit=1`))[0];if(c)await patch('rds_contacts',c.id,{total_purchases:Number(c.total_purchases||0)+1,total_orders:Number(c.total_orders||0)+1,last_interaction_at:now()})}if(connected)await sendText(o.phone,`${s.final_message}\nPedido: ${o.code}`);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/returns',async(req,res)=>{try{const conv=await sb('/rest/v1/rds_conversations?stage=neq.COMPRA_CONCLUIDA&select=*&order=updated_at.desc&limit=200');const items=[];for(const x of conv){const c=x.contact_id?(await sb(`/rest/v1/rds_contacts?id=eq.${q(x.contact_id)}&select=name,group_name&limit=1`))[0]:null;items.push({...x,name:c?.name||`WhatsApp ${x.phone.slice(-4)}`,group_name:c?.group_name||''})}res.json({items})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/returns/:id/read',async(req,res)=>{try{await patch('rds_conversations',req.params.id,{unread_count:0});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/returns/:id/start-order',async(req,res)=>{try{const c=(await sb(`/rest/v1/rds_conversations?id=eq.${q(req.params.id)}&select=*&limit=1`))[0];const contact=await ensureContact(c.phone);const rec=await activeRecipient(c.phone);await startOrder(c.phone,contact,rec,c.current_campaign_id,null);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/summary',async(req,res)=>{try{const [c,ca,d,o,cv]=await Promise.all([sb('/rest/v1/rds_contacts?status=eq.ATIVO&select=id'),sb('/rest/v1/rds_campaigns?archived=eq.false&select=id,status'),sb('/rest/v1/rds_deliveries?select=status'),sb('/rest/v1/rds_orders?select=id,status'),sb('/rest/v1/rds_conversations?select=id,stage,unread_count')]);res.json({contacts:c.length,campaigns:ca.length,scheduled:d.filter(x=>x.status==='AGENDADA').length,dispatched:d.filter(x=>['ENVIADA_SERVIDOR','ENTREGUE','LIDA'].includes(x.status)).length,delivered:d.filter(x=>['ENTREGUE','LIDA'].includes(x.status)).length,returns:cv.filter(x=>x.stage!=='COMPRA_CONCLUIDA').length,unread:cv.reduce((n,x)=>n+Number(x.unread_count||0),0),orders:o.length,proofs:o.filter(x=>x.status==='COMPROVANTE_RECEBIDO').length,purchases:o.filter(x=>x.status==='COMPRA_CONCLUIDA').length})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/activity',async(req,res)=>{try{res.json({items:await sb('/rest/v1/rds_events?select=*&order=created_at.desc&limit=30')})}catch(e){res.status(500).json({error:e.message})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.listen(PORT,async()=>{console.log(`CANAL DE VENDAS RDS V6.1 na porta ${PORT}`);try{await startWA(false)}catch(e){console.log('WhatsApp aguardando:',e.message)}});
