(()=>{
  const oldSettings=window.settings;
  const oldAutomation=window.automation;
  const hm=n=>{n=Number(n||0);const h=String(Math.floor(n/60)).padStart(2,'0'),m=String(n%60).padStart(2,'0');return `${h}:${m}`};
  const mins=t=>{const [h,m]=String(t||'08:00').split(':').map(Number);return Math.max(0,Math.min(1439,(h||0)*60+(m||0)))};
  window.rds1020Save=async function(){
    try{
      const body={enabled:document.querySelector('#rds1020Enabled').checked,collecting_enabled:document.querySelector('#rds1020CollectingEnabled').checked,collecting_delay:Number(document.querySelector('#rds1020CollectingDelay').value||30),payment_enabled:document.querySelector('#rds1020PaymentEnabled').checked,payment_delay:Number(document.querySelector('#rds1020PaymentDelay').value||60),payment_repeat:Number(document.querySelector('#rds1020PaymentRepeat').value||180),payment_max:Number(document.querySelector('#rds1020PaymentMax').value||2),proof_alert:Number(document.querySelector('#rds1020ProofAlert').value||20),tickets_alert:Number(document.querySelector('#rds1020TicketsAlert').value||20),quiet_start:mins(document.querySelector('#rds1020Start').value),quiet_end:mins(document.querySelector('#rds1020End').value),max_daily:Number(document.querySelector('#rds1020Daily').value||2),min_gap:Number(document.querySelector('#rds1020Gap').value||60),collecting_message:document.querySelector('#rds1020CollectingMessage').value,payment_message:document.querySelector('#rds1020PaymentMessage').value};
      await post('/api/v1020/final-config',body);toast('Lembretes e segurança salvos.');await settings();
    }catch(e){toast(e.message)}
  };
  window.settings=async function(){
    await oldSettings();
    try{
      const d=await api('/api/v1020/final-config');if(document.querySelector('#rds1020Final'))return;
      const box=document.createElement('div');box.id='rds1020Final';box.className='card';
      box.innerHTML=`<span class="eyebrow">FINALIZAÇÃO OPERACIONAL</span><h2>Lembretes e segurança</h2><p class="mut">Controle único dos lembretes do pedido. O sistema interrompe mensagens quando o cliente responde, conclui a compra, pede para parar ou atinge os limites de segurança.</p><label><input id="rds1020Enabled" type="checkbox" style="width:auto" ${d.enabled?'checked':''}> Ativar automação de lembretes</label><div class="grid"><div><label><input id="rds1020CollectingEnabled" type="checkbox" style="width:auto" ${d.collecting_enabled?'checked':''}> Lembrar dados do pedido</label><input id="rds1020CollectingDelay" type="number" min="5" max="1440" value="${Number(d.collecting_delay||30)}"><p class="mini">minutos após iniciar pedido</p></div><div><label><input id="rds1020PaymentEnabled" type="checkbox" style="width:auto" ${d.payment_enabled?'checked':''}> Lembrar pagamento PIX</label><input id="rds1020PaymentDelay" type="number" min="5" max="2880" value="${Number(d.payment_delay||60)}"><p class="mini">minutos para o primeiro lembrete</p></div><div><label>Repetir PIX após</label><input id="rds1020PaymentRepeat" type="number" min="30" max="2880" value="${Number(d.payment_repeat||180)}"><p class="mini">minutos entre lembretes</p></div><div><label>Máximo de lembretes PIX</label><input id="rds1020PaymentMax" type="number" min="1" max="3" value="${Number(d.payment_max||2)}"></div><div><label>Alertar conferência após</label><input id="rds1020ProofAlert" type="number" min="5" max="1440" value="${Number(d.proof_alert||20)}"><p class="mini">minutos • alerta interno</p></div><div><label>Alertar bilhetes após</label><input id="rds1020TicketsAlert" type="number" min="5" max="1440" value="${Number(d.tickets_alert||20)}"><p class="mini">minutos • alerta interno</p></div></div><h3>Proteção contra excesso de mensagens</h3><div class="grid"><div><label>Enviar somente a partir de</label><input id="rds1020Start" type="time" value="${hm(d.quiet_start)}"></div><div><label>Enviar somente até</label><input id="rds1020End" type="time" value="${hm(d.quiet_end)}"></div><div><label>Máximo por cliente/dia</label><input id="rds1020Daily" type="number" min="1" max="5" value="${Number(d.max_daily||2)}"></div><div><label>Intervalo mínimo</label><input id="rds1020Gap" type="number" min="15" max="1440" value="${Number(d.min_gap||60)}"><p class="mini">minutos</p></div></div><label>Mensagem — dados pendentes</label><textarea id="rds1020CollectingMessage">${esc(d.collecting_message||'')}</textarea><label>Mensagem — PIX pendente</label><textarea id="rds1020PaymentMessage">${esc(d.payment_message||'')}</textarea><p class="mini">Variáveis: {NOME}, {PEDIDO}, {VALOR}. Palavras de bloqueio reconhecidas: SAIR, PARAR, NÃO QUERO RECEBER e CANCELAR MENSAGENS.</p><div class="row"><button class="btn primary" onclick="rds1020Save()">Salvar configuração final</button></div>`;
      const old=document.querySelector('#rds1019Box');if(old)old.insertAdjacentElement('afterend',box);else app.appendChild(box);
    }catch(e){console.error('V10.20 settings',e)}
  };
  window.automation=async function(){
    await oldAutomation();
    try{
      const d=await api('/api/v1020/summary');if(document.querySelector('#rds1020Summary'))return;
      const box=document.createElement('div');box.id='rds1020Summary';box.className='card';
      box.innerHTML=`<span class="eyebrow">LEMBRETES DE VENDAS</span><h2>Fluxo protegido</h2><div class="grid"><div class="card"><span class="eyebrow">DADOS PENDENTES</span><div class="metric">${Number(d.collecting||0)}</div></div><div class="card"><span class="eyebrow">PIX PENDENTE</span><div class="metric">${Number(d.payment||0)}</div></div><div class="card"><span class="eyebrow">CONFERIR</span><div class="metric">${Number(d.proof||0)}</div></div><div class="card"><span class="eyebrow">ENVIAR BILHETES</span><div class="metric">${Number(d.tickets||0)}</div></div></div><p class="mini">Automação: <b>${d.enabled?'ATIVA':'DESATIVADA'}</b> • Horário seguro agora: <b>${d.safe_window?'SIM':'NÃO'}</b> • Limite diário por cliente: ${Number(d.max_daily||0)}</p>`;
      const title=document.querySelector('#app .page-title');if(title)title.insertAdjacentElement('afterend',box);else app.prepend(box);
    }catch(e){console.error('V10.20 automation',e)}
  };
})();
